rename 's/_RA_GGCCATCCTC.fastq/FW-Combo5-001_RA.fastq/' _RA_GGCCATCCTC.fastq
rename 's/_RA_GGAATGTTGC.fastq/FW-Combo5-002_RA.fastq/' _RA_GGAATGTTGC.fastq
rename 's/_RA_GGTATCAGCA.fastq/FW-Combo5-003_RA.fastq/' _RA_GGTATCAGCA.fastq
rename 's/_RA_GGGATAGACA.fastq/FW-Combo5-004_RA.fastq/' _RA_GGGATAGACA.fastq
rename 's/_RA_GGCCGAAGTA.fastq/FW-Combo5-005_RA.fastq/' _RA_GGCCGAAGTA.fastq
rename 's/_RA_GGAGATCGCA.fastq/FW-Combo5-006_RA.fastq/' _RA_GGAGATCGCA.fastq
rename 's/_RA_GGAACAACCA.fastq/FW-Combo5-007_RA.fastq/' _RA_GGAACAACCA.fastq
rename 's/_RA_GGACAAGCTA.fastq/FW-Combo5-008_RA.fastq/' _RA_GGACAAGCTA.fastq
rename 's/_RA_GGCCGACAAC.fastq/FW-Combo5-009_RA.fastq/' _RA_GGCCGACAAC.fastq
rename 's/_RA_GGACACTGAC.fastq/FW-Combo5-010_RA.fastq/' _RA_GGACACTGAC.fastq
rename 's/_RA_GGTCCGTCTA.fastq/FW-Combo5-011_RA.fastq/' _RA_GGTCCGTCTA.fastq
rename 's/_RA_GGGCCACATA.fastq/FW-Combo5-012_RA.fastq/' _RA_GGGCCACATA.fastq
rename 's/_RA_GGCCGTGAGA.fastq/FW-Combo5-013_RA.fastq/' _RA_GGCCGTGAGA.fastq
rename 's/_RA_GGAGCAGGAA.fastq/FW-Combo5-014_RA.fastq/' _RA_GGAGCAGGAA.fastq
rename 's/_RA_GGAACCGAGA.fastq/FW-Combo5-015_RA.fastq/' _RA_GGAACCGAGA.fastq
rename 's/_RA_GGAAACATCG.fastq/FW-Combo5-016_RA.fastq/' _RA_GGAAACATCG.fastq
rename 's/_RA_GGAGTCAAGC.fastq/FW-Combo5-017_RA.fastq/' _RA_GGAGTCAAGC.fastq
rename 's/_RA_GGACAGATTC.fastq/FW-Combo5-018_RA.fastq/' _RA_GGACAGATTC.fastq
rename 's/_RA_GGTCTTCACA.fastq/FW-Combo5-019_RA.fastq/' _RA_GGTCTTCACA.fastq
rename 's/_RA_GGGCGAGTAA.fastq/FW-Combo5-020_RA.fastq/' _RA_GGGCGAGTAA.fastq
rename 's/_RA_GGCCTCCTGA.fastq/FW-Combo5-021_RA.fastq/' _RA_GGCCTCCTGA.fastq
rename 's/_RA_GGAGTCACTA.fastq/FW-Combo5-022_RA.fastq/' _RA_GGAGTCACTA.fastq
rename 's/_RA_GGAACGCTTA.fastq/FW-Combo5-023_RA.fastq/' _RA_GGAACGCTTA.fastq
rename 's/_RA_GGACATTGGC.fastq/FW-Combo5-024_RA.fastq/' _RA_GGACATTGGC.fastq
rename 's/_RA_GGCCTCTATC.fastq/FW-Combo5-025_RA.fastq/' _RA_GGCCTCTATC.fastq
rename 's/_RA_GGAGATGTAC.fastq/FW-Combo5-026_RA.fastq/' _RA_GGAGATGTAC.fastq
rename 's/_RA_GGTGAAGAGA.fastq/FW-Combo5-027_RA.fastq/' _RA_GGTGAAGAGA.fastq
rename 's/_RA_GGGCTAACGA.fastq/FW-Combo5-028_RA.fastq/' _RA_GGGCTAACGA.fastq
rename 's/_RA_GGCGAACTTA.fastq/FW-Combo5-029_RA.fastq/' _RA_GGCGAACTTA.fastq
rename 's/_RA_GGATCCTGTA.fastq/FW-Combo5-030_RA.fastq/' _RA_GGATCCTGTA.fastq
rename 's/_RA_GGAAGACGGA.fastq/FW-Combo5-031_RA.fastq/' _RA_GGAAGACGGA.fastq
rename 's/_RA_GGACCACTGT.fastq/FW-Combo5-032_RA.fastq/' _RA_GGACCACTGT.fastq
rename 's/_RA_GGCGACACAC.fastq/FW-Combo5-033_RA.fastq/' _RA_GGCGACACAC.fastq
rename 's/_RA_GGAGCACCTC.fastq/FW-Combo5-034_RA.fastq/' _RA_GGAGCACCTC.fastq
rename 's/_RA_GGTGGAACAA.fastq/FW-Combo5-035_RA.fastq/' _RA_GGTGGAACAA.fastq
rename 's/_RA_GGGCTCGGTA.fastq/FW-Combo5-036_RA.fastq/' _RA_GGGCTCGGTA.fastq
rename 's/_RA_GGCGACTGGA.fastq/FW-Combo5-037_RA.fastq/' _RA_GGCGACTGGA.fastq
rename 's/_RA_GGATTGAGGA.fastq/FW-Combo5-038_RA.fastq/' _RA_GGATTGAGGA.fastq
rename 's/_RA_GGAAGGTACA.fastq/FW-Combo5-039_RA.fastq/' _RA_GGAAGGTACA.fastq
rename 's/_RA_GGAACGTGAT.fastq/FW-Combo5-040_RA.fastq/' _RA_GGAACGTGAT.fastq
rename 's/_RA_GGCGGATTGC.fastq/FW-Combo5-041_RA.fastq/' _RA_GGCGGATTGC.fastq
rename 's/_RA_GGAGCCATGC.fastq/FW-Combo5-042_RA.fastq/' _RA_GGAGCCATGC.fastq
rename 's/_RA_GGTGGCTTCA.fastq/FW-Combo5-043_RA.fastq/' _RA_GGTGGCTTCA.fastq
rename 's/_RA_GGGGAGAACA.fastq/FW-Combo5-044_RA.fastq/' _RA_GGGGAGAACA.fastq
rename 's/_RA_GGCGCATACA.fastq/FW-Combo5-045_RA.fastq/' _RA_GGCGCATACA.fastq
rename 's/_RA_GGCAACCACA.fastq/FW-Combo5-046_RA.fastq/' _RA_GGCAACCACA.fastq
rename 's/_RA_GGACACAGAA.fastq/FW-Combo5-047_RA.fastq/' _RA_GGACACAGAA.fastq
rename 's/_RA_GGCGCTGATC.fastq/FW-Combo5-048_RA.fastq/' _RA_GGCGCTGATC.fastq
rename 's/_RA_GGCTAAGGTC.fastq/FW-Combo5-049_RA.fastq/' _RA_GGCTAAGGTC.fastq
rename 's/_RA_GGAGGCTAAC.fastq/FW-Combo5-050_RA.fastq/' _RA_GGAGGCTAAC.fastq
rename 's/_RA_GGTGGTGGTA.fastq/FW-Combo5-051_RA.fastq/' _RA_GGTGGTGGTA.fastq
rename 's/_RA_GGGGTGCGAA.fastq/FW-Combo5-052_RA.fastq/' _RA_GGGGTGCGAA.fastq
rename 's/_RA_GGCTCAATGA.fastq/FW-Combo5-053_RA.fastq/' _RA_GGCTCAATGA.fastq
rename 's/_RA_GGCAAGACTA.fastq/FW-Combo5-054_RA.fastq/' _RA_GGCAAGACTA.fastq
rename 's/_RA_GGACAGCAGA.fastq/FW-Combo5-055_RA.fastq/' _RA_GGACAGCAGA.fastq
rename 's/_RA_GGCAGATCTG.fastq/FW-Combo5-056_RA.fastq/' _RA_GGCAGATCTG.fastq
rename 's/_RA_GGGAACAGGC.fastq/FW-Combo5-057_RA.fastq/' _RA_GGGAACAGGC.fastq
rename 's/_RA_GGATAGCGAC.fastq/FW-Combo5-058_RA.fastq/' _RA_GGATAGCGAC.fastq
rename 's/_RA_GGTTCACGCA.fastq/FW-Combo5-059_RA.fastq/' _RA_GGTTCACGCA.fastq
rename 's/_RA_GGGTACGCAA.fastq/FW-Combo5-060_RA.fastq/' _RA_GGGTACGCAA.fastq
rename 's/_RA_GGCTGAGCCA.fastq/FW-Combo5-061_RA.fastq/' _RA_GGCTGAGCCA.fastq
rename 's/_RA_GGCAATGGAA.fastq/FW-Combo5-062_RA.fastq/' _RA_GGCAATGGAA.fastq
rename 's/_RA_GGACCTCCAA.fastq/FW-Combo5-063_RA.fastq/' _RA_GGACCTCCAA.fastq
rename 's/_RA_GGATGCCTAA.fastq/FW-Combo5-064_RA.fastq/' _RA_GGATGCCTAA.fastq
rename 's/_RA_GGGACAGTGC.fastq/FW-Combo5-065_RA.fastq/' _RA_GGGACAGTGC.fastq
rename 's/_RA_GGACGACAAG.fastq/FW-Combo5-066_RA.fastq/' _RA_GGACGACAAG.fastq
rename 's/_RA_GGACACGAGA.fastq/FW-Combo5-067_RA.fastq/' _RA_GGACACGAGA.fastq
rename 's/_RA_GGGTCGTAGA.fastq/FW-Combo5-068_RA.fastq/' _RA_GGGTCGTAGA.fastq
rename 's/_RA_GGCTGGCATA.fastq/FW-Combo5-069_RA.fastq/' _RA_GGCTGGCATA.fastq
rename 's/_RA_GGCACTTCGA.fastq/FW-Combo5-070_RA.fastq/' _RA_GGCACTTCGA.fastq
rename 's/_RA_GGACGCTCGA.fastq/FW-Combo5-071_RA.fastq/' _RA_GGACGCTCGA.fastq
rename 's/_RA_GGAACGAACG.fastq/FW-Combo5-072_RA.fastq/' _RA_GGAACGAACG.fastq
rename 's/_RA_GGGAGTTAGC.fastq/FW-Combo5-073_RA.fastq/' _RA_GGGAGTTAGC.fastq
rename 's/_RA_GGATTGGCTC.fastq/FW-Combo5-074_RA.fastq/' _RA_GGATTGGCTC.fastq
rename 's/_RA_GGAAGAGATC.fastq/FW-Combo5-075_RA.fastq/' _RA_GGAAGAGATC.fastq
rename 's/_RA_GGGTCTGTCA.fastq/FW-Combo5-076_RA.fastq/' _RA_GGGTCTGTCA.fastq
rename 's/_RA_GGGAATCTGA.fastq/FW-Combo5-077_RA.fastq/' _RA_GGGAATCTGA.fastq
rename 's/_RA_GGCAGCGTTA.fastq/FW-Combo5-078_RA.fastq/' _RA_GGCAGCGTTA.fastq
rename 's/_RA_GGACGTATCA.fastq/FW-Combo5-079_RA.fastq/' _RA_GGACGTATCA.fastq
rename 's/_RA_GGAGTACAAG.fastq/FW-Combo5-080_RA.fastq/' _RA_GGAGTACAAG.fastq
rename 's/_RA_GGGATGAATC.fastq/FW-Combo5-081_RA.fastq/' _RA_GGGATGAATC.fastq
rename 's/_RA_GGCAAGGAGC.fastq/FW-Combo5-082_RA.fastq/' _RA_GGCAAGGAGC.fastq
rename 's/_RA_GGAAGGACAC.fastq/FW-Combo5-083_RA.fastq/' _RA_GGAAGGACAC.fastq
rename 's/_RA_GGGTGTTCTA.fastq/FW-Combo5-084_RA.fastq/' _RA_GGGTGTTCTA.fastq
rename 's/_RA_GGGACTAGTA.fastq/FW-Combo5-085_RA.fastq/' _RA_GGGACTAGTA.fastq
rename 's/_RA_GGCATACCAA.fastq/FW-Combo5-086_RA.fastq/' _RA_GGCATACCAA.fastq
rename 's/_RA_GGACTATGCA.fastq/FW-Combo5-087_RA.fastq/' _RA_GGACTATGCA.fastq
rename 's/_RA_GGCATCAAGT.fastq/FW-Combo5-088_RA.fastq/' _RA_GGCATCAAGT.fastq
rename 's/_RA_GGGCCAAGAC.fastq/FW-Combo5-089_RA.fastq/' _RA_GGGCCAAGAC.fastq
rename 's/_RA_GGCACCTTAC.fastq/FW-Combo5-090_RA.fastq/' _RA_GGCACCTTAC.fastq
rename 's/_RA_GGAATCCGTC.fastq/FW-Combo5-091_RA.fastq/' _RA_GGAATCCGTC.fastq
rename 's/_RA_GGTAGGATGA.fastq/FW-Combo5-092_RA.fastq/' _RA_GGTAGGATGA.fastq
rename 's/_RA_GGGAGCTGAA.fastq/FW-Combo5-093_RA.fastq/' _RA_GGGAGCTGAA.fastq
rename 's/_RA_GGCCAGTTCA.fastq/FW-Combo5-094_RA.fastq/' _RA_GGCCAGTTCA.fastq
rename 's/_RA_GGAGAGTCAA.fastq/FW-Combo5-095_RA.fastq/' _RA_GGAGAGTCAA.fastq
rename 's/_RA_GGAGTGGTCA.fastq/FW-Combo5-096_RA.fastq/' _RA_GGAGTGGTCA.fastq
rename 's/_RB_GGCCATCCTC.fastq/FW-Combo5-001_RB.fastq/' _RB_GGCCATCCTC.fastq
rename 's/_RB_GGAATGTTGC.fastq/FW-Combo5-002_RB.fastq/' _RB_GGAATGTTGC.fastq
rename 's/_RB_GGTATCAGCA.fastq/FW-Combo5-003_RB.fastq/' _RB_GGTATCAGCA.fastq
rename 's/_RB_GGGATAGACA.fastq/FW-Combo5-004_RB.fastq/' _RB_GGGATAGACA.fastq
rename 's/_RB_GGCCGAAGTA.fastq/FW-Combo5-005_RB.fastq/' _RB_GGCCGAAGTA.fastq
rename 's/_RB_GGAGATCGCA.fastq/FW-Combo5-006_RB.fastq/' _RB_GGAGATCGCA.fastq
rename 's/_RB_GGAACAACCA.fastq/FW-Combo5-007_RB.fastq/' _RB_GGAACAACCA.fastq
rename 's/_RB_GGACAAGCTA.fastq/FW-Combo5-008_RB.fastq/' _RB_GGACAAGCTA.fastq
rename 's/_RB_GGCCGACAAC.fastq/FW-Combo5-009_RB.fastq/' _RB_GGCCGACAAC.fastq
rename 's/_RB_GGACACTGAC.fastq/FW-Combo5-010_RB.fastq/' _RB_GGACACTGAC.fastq
rename 's/_RB_GGTCCGTCTA.fastq/FW-Combo5-011_RB.fastq/' _RB_GGTCCGTCTA.fastq
rename 's/_RB_GGGCCACATA.fastq/FW-Combo5-012_RB.fastq/' _RB_GGGCCACATA.fastq
rename 's/_RB_GGCCGTGAGA.fastq/FW-Combo5-013_RB.fastq/' _RB_GGCCGTGAGA.fastq
rename 's/_RB_GGAGCAGGAA.fastq/FW-Combo5-014_RB.fastq/' _RB_GGAGCAGGAA.fastq
rename 's/_RB_GGAACCGAGA.fastq/FW-Combo5-015_RB.fastq/' _RB_GGAACCGAGA.fastq
rename 's/_RB_GGAAACATCG.fastq/FW-Combo5-016_RB.fastq/' _RB_GGAAACATCG.fastq
rename 's/_RB_GGAGTCAAGC.fastq/FW-Combo5-017_RB.fastq/' _RB_GGAGTCAAGC.fastq
rename 's/_RB_GGACAGATTC.fastq/FW-Combo5-018_RB.fastq/' _RB_GGACAGATTC.fastq
rename 's/_RB_GGTCTTCACA.fastq/FW-Combo5-019_RB.fastq/' _RB_GGTCTTCACA.fastq
rename 's/_RB_GGGCGAGTAA.fastq/FW-Combo5-020_RB.fastq/' _RB_GGGCGAGTAA.fastq
rename 's/_RB_GGCCTCCTGA.fastq/FW-Combo5-021_RB.fastq/' _RB_GGCCTCCTGA.fastq
rename 's/_RB_GGAGTCACTA.fastq/FW-Combo5-022_RB.fastq/' _RB_GGAGTCACTA.fastq
rename 's/_RB_GGAACGCTTA.fastq/FW-Combo5-023_RB.fastq/' _RB_GGAACGCTTA.fastq
rename 's/_RB_GGACATTGGC.fastq/FW-Combo5-024_RB.fastq/' _RB_GGACATTGGC.fastq
rename 's/_RB_GGCCTCTATC.fastq/FW-Combo5-025_RB.fastq/' _RB_GGCCTCTATC.fastq
rename 's/_RB_GGAGATGTAC.fastq/FW-Combo5-026_RB.fastq/' _RB_GGAGATGTAC.fastq
rename 's/_RB_GGTGAAGAGA.fastq/FW-Combo5-027_RB.fastq/' _RB_GGTGAAGAGA.fastq
rename 's/_RB_GGGCTAACGA.fastq/FW-Combo5-028_RB.fastq/' _RB_GGGCTAACGA.fastq
rename 's/_RB_GGCGAACTTA.fastq/FW-Combo5-029_RB.fastq/' _RB_GGCGAACTTA.fastq
rename 's/_RB_GGATCCTGTA.fastq/FW-Combo5-030_RB.fastq/' _RB_GGATCCTGTA.fastq
rename 's/_RB_GGAAGACGGA.fastq/FW-Combo5-031_RB.fastq/' _RB_GGAAGACGGA.fastq
rename 's/_RB_GGACCACTGT.fastq/FW-Combo5-032_RB.fastq/' _RB_GGACCACTGT.fastq
rename 's/_RB_GGCGACACAC.fastq/FW-Combo5-033_RB.fastq/' _RB_GGCGACACAC.fastq
rename 's/_RB_GGAGCACCTC.fastq/FW-Combo5-034_RB.fastq/' _RB_GGAGCACCTC.fastq
rename 's/_RB_GGTGGAACAA.fastq/FW-Combo5-035_RB.fastq/' _RB_GGTGGAACAA.fastq
rename 's/_RB_GGGCTCGGTA.fastq/FW-Combo5-036_RB.fastq/' _RB_GGGCTCGGTA.fastq
rename 's/_RB_GGCGACTGGA.fastq/FW-Combo5-037_RB.fastq/' _RB_GGCGACTGGA.fastq
rename 's/_RB_GGATTGAGGA.fastq/FW-Combo5-038_RB.fastq/' _RB_GGATTGAGGA.fastq
rename 's/_RB_GGAAGGTACA.fastq/FW-Combo5-039_RB.fastq/' _RB_GGAAGGTACA.fastq
rename 's/_RB_GGAACGTGAT.fastq/FW-Combo5-040_RB.fastq/' _RB_GGAACGTGAT.fastq
rename 's/_RB_GGCGGATTGC.fastq/FW-Combo5-041_RB.fastq/' _RB_GGCGGATTGC.fastq
rename 's/_RB_GGAGCCATGC.fastq/FW-Combo5-042_RB.fastq/' _RB_GGAGCCATGC.fastq
rename 's/_RB_GGTGGCTTCA.fastq/FW-Combo5-043_RB.fastq/' _RB_GGTGGCTTCA.fastq
rename 's/_RB_GGGGAGAACA.fastq/FW-Combo5-044_RB.fastq/' _RB_GGGGAGAACA.fastq
rename 's/_RB_GGCGCATACA.fastq/FW-Combo5-045_RB.fastq/' _RB_GGCGCATACA.fastq
rename 's/_RB_GGCAACCACA.fastq/FW-Combo5-046_RB.fastq/' _RB_GGCAACCACA.fastq
rename 's/_RB_GGACACAGAA.fastq/FW-Combo5-047_RB.fastq/' _RB_GGACACAGAA.fastq
rename 's/_RB_GGCGCTGATC.fastq/FW-Combo5-048_RB.fastq/' _RB_GGCGCTGATC.fastq
rename 's/_RB_GGCTAAGGTC.fastq/FW-Combo5-049_RB.fastq/' _RB_GGCTAAGGTC.fastq
rename 's/_RB_GGAGGCTAAC.fastq/FW-Combo5-050_RB.fastq/' _RB_GGAGGCTAAC.fastq
rename 's/_RB_GGTGGTGGTA.fastq/FW-Combo5-051_RB.fastq/' _RB_GGTGGTGGTA.fastq
rename 's/_RB_GGGGTGCGAA.fastq/FW-Combo5-052_RB.fastq/' _RB_GGGGTGCGAA.fastq
rename 's/_RB_GGCTCAATGA.fastq/FW-Combo5-053_RB.fastq/' _RB_GGCTCAATGA.fastq
rename 's/_RB_GGCAAGACTA.fastq/FW-Combo5-054_RB.fastq/' _RB_GGCAAGACTA.fastq
rename 's/_RB_GGACAGCAGA.fastq/FW-Combo5-055_RB.fastq/' _RB_GGACAGCAGA.fastq
rename 's/_RB_GGCAGATCTG.fastq/FW-Combo5-056_RB.fastq/' _RB_GGCAGATCTG.fastq
rename 's/_RB_GGGAACAGGC.fastq/FW-Combo5-057_RB.fastq/' _RB_GGGAACAGGC.fastq
rename 's/_RB_GGATAGCGAC.fastq/FW-Combo5-058_RB.fastq/' _RB_GGATAGCGAC.fastq
rename 's/_RB_GGTTCACGCA.fastq/FW-Combo5-059_RB.fastq/' _RB_GGTTCACGCA.fastq
rename 's/_RB_GGGTACGCAA.fastq/FW-Combo5-060_RB.fastq/' _RB_GGGTACGCAA.fastq
rename 's/_RB_GGCTGAGCCA.fastq/FW-Combo5-061_RB.fastq/' _RB_GGCTGAGCCA.fastq
rename 's/_RB_GGCAATGGAA.fastq/FW-Combo5-062_RB.fastq/' _RB_GGCAATGGAA.fastq
rename 's/_RB_GGACCTCCAA.fastq/FW-Combo5-063_RB.fastq/' _RB_GGACCTCCAA.fastq
rename 's/_RB_GGATGCCTAA.fastq/FW-Combo5-064_RB.fastq/' _RB_GGATGCCTAA.fastq
rename 's/_RB_GGGACAGTGC.fastq/FW-Combo5-065_RB.fastq/' _RB_GGGACAGTGC.fastq
rename 's/_RB_GGACGACAAG.fastq/FW-Combo5-066_RB.fastq/' _RB_GGACGACAAG.fastq
rename 's/_RB_GGACACGAGA.fastq/FW-Combo5-067_RB.fastq/' _RB_GGACACGAGA.fastq
rename 's/_RB_GGGTCGTAGA.fastq/FW-Combo5-068_RB.fastq/' _RB_GGGTCGTAGA.fastq
rename 's/_RB_GGCTGGCATA.fastq/FW-Combo5-069_RB.fastq/' _RB_GGCTGGCATA.fastq
rename 's/_RB_GGCACTTCGA.fastq/FW-Combo5-070_RB.fastq/' _RB_GGCACTTCGA.fastq
rename 's/_RB_GGACGCTCGA.fastq/FW-Combo5-071_RB.fastq/' _RB_GGACGCTCGA.fastq
rename 's/_RB_GGAACGAACG.fastq/FW-Combo5-072_RB.fastq/' _RB_GGAACGAACG.fastq
rename 's/_RB_GGGAGTTAGC.fastq/FW-Combo5-073_RB.fastq/' _RB_GGGAGTTAGC.fastq
rename 's/_RB_GGATTGGCTC.fastq/FW-Combo5-074_RB.fastq/' _RB_GGATTGGCTC.fastq
rename 's/_RB_GGAAGAGATC.fastq/FW-Combo5-075_RB.fastq/' _RB_GGAAGAGATC.fastq
rename 's/_RB_GGGTCTGTCA.fastq/FW-Combo5-076_RB.fastq/' _RB_GGGTCTGTCA.fastq
rename 's/_RB_GGGAATCTGA.fastq/FW-Combo5-077_RB.fastq/' _RB_GGGAATCTGA.fastq
rename 's/_RB_GGCAGCGTTA.fastq/FW-Combo5-078_RB.fastq/' _RB_GGCAGCGTTA.fastq
rename 's/_RB_GGACGTATCA.fastq/FW-Combo5-079_RB.fastq/' _RB_GGACGTATCA.fastq
rename 's/_RB_GGAGTACAAG.fastq/FW-Combo5-080_RB.fastq/' _RB_GGAGTACAAG.fastq
rename 's/_RB_GGGATGAATC.fastq/FW-Combo5-081_RB.fastq/' _RB_GGGATGAATC.fastq
rename 's/_RB_GGCAAGGAGC.fastq/FW-Combo5-082_RB.fastq/' _RB_GGCAAGGAGC.fastq
rename 's/_RB_GGAAGGACAC.fastq/FW-Combo5-083_RB.fastq/' _RB_GGAAGGACAC.fastq
rename 's/_RB_GGGTGTTCTA.fastq/FW-Combo5-084_RB.fastq/' _RB_GGGTGTTCTA.fastq
rename 's/_RB_GGGACTAGTA.fastq/FW-Combo5-085_RB.fastq/' _RB_GGGACTAGTA.fastq
rename 's/_RB_GGCATACCAA.fastq/FW-Combo5-086_RB.fastq/' _RB_GGCATACCAA.fastq
rename 's/_RB_GGACTATGCA.fastq/FW-Combo5-087_RB.fastq/' _RB_GGACTATGCA.fastq
rename 's/_RB_GGCATCAAGT.fastq/FW-Combo5-088_RB.fastq/' _RB_GGCATCAAGT.fastq
rename 's/_RB_GGGCCAAGAC.fastq/FW-Combo5-089_RB.fastq/' _RB_GGGCCAAGAC.fastq
rename 's/_RB_GGCACCTTAC.fastq/FW-Combo5-090_RB.fastq/' _RB_GGCACCTTAC.fastq
rename 's/_RB_GGAATCCGTC.fastq/FW-Combo5-091_RB.fastq/' _RB_GGAATCCGTC.fastq
rename 's/_RB_GGTAGGATGA.fastq/FW-Combo5-092_RB.fastq/' _RB_GGTAGGATGA.fastq
rename 's/_RB_GGGAGCTGAA.fastq/FW-Combo5-093_RB.fastq/' _RB_GGGAGCTGAA.fastq
rename 's/_RB_GGCCAGTTCA.fastq/FW-Combo5-094_RB.fastq/' _RB_GGCCAGTTCA.fastq
rename 's/_RB_GGAGAGTCAA.fastq/FW-Combo5-095_RB.fastq/' _RB_GGAGAGTCAA.fastq
rename 's/_RB_GGAGTGGTCA.fastq/FW-Combo5-096_RB.fastq/' _RB_GGAGTGGTCA.fastq
