rename 's/_RA_GGCCATCCTC.fastq/BW-Combo3-001_RA.fastq/' _RA_GGCCATCCTC.fastq
rename 's/_RA_GGAATGTTGC.fastq/BW-Combo3-002_RA.fastq/' _RA_GGAATGTTGC.fastq
rename 's/_RA_GGTATCAGCA.fastq/BW-Combo3-003_RA.fastq/' _RA_GGTATCAGCA.fastq
rename 's/_RA_GGGATAGACA.fastq/BW-Combo3-004_RA.fastq/' _RA_GGGATAGACA.fastq
rename 's/_RA_GGCCGAAGTA.fastq/BW-Combo3-005_RA.fastq/' _RA_GGCCGAAGTA.fastq
rename 's/_RA_GGAGATCGCA.fastq/BW-Combo3-006_RA.fastq/' _RA_GGAGATCGCA.fastq
rename 's/_RA_GGAACAACCA.fastq/BW-Combo3-007_RA.fastq/' _RA_GGAACAACCA.fastq
rename 's/_RA_GGACAAGCTA.fastq/BW-Combo3-008_RA.fastq/' _RA_GGACAAGCTA.fastq
rename 's/_RA_GGCCGACAAC.fastq/BW-Combo3-009_RA.fastq/' _RA_GGCCGACAAC.fastq
rename 's/_RA_GGACACTGAC.fastq/BW-Combo3-010_RA.fastq/' _RA_GGACACTGAC.fastq
rename 's/_RA_GGTCCGTCTA.fastq/BW-Combo3-011_RA.fastq/' _RA_GGTCCGTCTA.fastq
rename 's/_RA_GGGCCACATA.fastq/BW-Combo3-012_RA.fastq/' _RA_GGGCCACATA.fastq
rename 's/_RA_GGCCGTGAGA.fastq/BW-Combo3-013_RA.fastq/' _RA_GGCCGTGAGA.fastq
rename 's/_RA_GGAGCAGGAA.fastq/BW-Combo3-014_RA.fastq/' _RA_GGAGCAGGAA.fastq
rename 's/_RA_GGAACCGAGA.fastq/BW-Combo3-015_RA.fastq/' _RA_GGAACCGAGA.fastq
rename 's/_RA_GGAAACATCG.fastq/BW-Combo3-016_RA.fastq/' _RA_GGAAACATCG.fastq
rename 's/_RA_GGAGTCAAGC.fastq/BW-Combo3-017_RA.fastq/' _RA_GGAGTCAAGC.fastq
rename 's/_RA_GGACAGATTC.fastq/BW-Combo3-018_RA.fastq/' _RA_GGACAGATTC.fastq
rename 's/_RA_GGTCTTCACA.fastq/BW-Combo3-019_RA.fastq/' _RA_GGTCTTCACA.fastq
rename 's/_RA_GGGCGAGTAA.fastq/BW-Combo3-020_RA.fastq/' _RA_GGGCGAGTAA.fastq
rename 's/_RA_GGCCTCCTGA.fastq/BW-Combo3-021_RA.fastq/' _RA_GGCCTCCTGA.fastq
rename 's/_RA_GGAGTCACTA.fastq/BW-Combo3-022_RA.fastq/' _RA_GGAGTCACTA.fastq
rename 's/_RA_GGAACGCTTA.fastq/BW-Combo3-023_RA.fastq/' _RA_GGAACGCTTA.fastq
rename 's/_RA_GGACATTGGC.fastq/BW-Combo3-024_RA.fastq/' _RA_GGACATTGGC.fastq
rename 's/_RA_GGCCTCTATC.fastq/BW-Combo3-025_RA.fastq/' _RA_GGCCTCTATC.fastq
rename 's/_RA_GGAGATGTAC.fastq/BW-Combo3-026_RA.fastq/' _RA_GGAGATGTAC.fastq
rename 's/_RA_GGTGAAGAGA.fastq/BW-Combo3-027_RA.fastq/' _RA_GGTGAAGAGA.fastq
rename 's/_RA_GGGCTAACGA.fastq/BW-Combo3-028_RA.fastq/' _RA_GGGCTAACGA.fastq
rename 's/_RA_GGCGAACTTA.fastq/BW-Combo3-029_RA.fastq/' _RA_GGCGAACTTA.fastq
rename 's/_RA_GGATCCTGTA.fastq/BW-Combo3-030_RA.fastq/' _RA_GGATCCTGTA.fastq
rename 's/_RA_GGAAGACGGA.fastq/BW-Combo3-031_RA.fastq/' _RA_GGAAGACGGA.fastq
rename 's/_RA_GGACCACTGT.fastq/BW-Combo3-032_RA.fastq/' _RA_GGACCACTGT.fastq
rename 's/_RA_GGCGACACAC.fastq/BW-Combo3-033_RA.fastq/' _RA_GGCGACACAC.fastq
rename 's/_RA_GGAGCACCTC.fastq/BW-Combo3-034_RA.fastq/' _RA_GGAGCACCTC.fastq
rename 's/_RA_GGTGGAACAA.fastq/BW-Combo3-035_RA.fastq/' _RA_GGTGGAACAA.fastq
rename 's/_RA_GGGCTCGGTA.fastq/BW-Combo3-036_RA.fastq/' _RA_GGGCTCGGTA.fastq
rename 's/_RA_GGCGACTGGA.fastq/BW-Combo3-037_RA.fastq/' _RA_GGCGACTGGA.fastq
rename 's/_RA_GGATTGAGGA.fastq/BW-Combo3-038_RA.fastq/' _RA_GGATTGAGGA.fastq
rename 's/_RA_GGAAGGTACA.fastq/BW-Combo3-039_RA.fastq/' _RA_GGAAGGTACA.fastq
rename 's/_RA_GGAACGTGAT.fastq/BW-Combo3-040_RA.fastq/' _RA_GGAACGTGAT.fastq
rename 's/_RA_GGCGGATTGC.fastq/BW-Combo3-041_RA.fastq/' _RA_GGCGGATTGC.fastq
rename 's/_RA_GGAGCCATGC.fastq/BW-Combo3-042_RA.fastq/' _RA_GGAGCCATGC.fastq
rename 's/_RA_GGTGGCTTCA.fastq/BW-Combo3-043_RA.fastq/' _RA_GGTGGCTTCA.fastq
rename 's/_RA_GGGGAGAACA.fastq/BW-Combo3-044_RA.fastq/' _RA_GGGGAGAACA.fastq
rename 's/_RA_GGCGCATACA.fastq/BW-Combo3-045_RA.fastq/' _RA_GGCGCATACA.fastq
rename 's/_RA_GGCAACCACA.fastq/BW-Combo3-046_RA.fastq/' _RA_GGCAACCACA.fastq
rename 's/_RA_GGACACAGAA.fastq/BW-Combo3-047_RA.fastq/' _RA_GGACACAGAA.fastq
rename 's/_RA_GGCGCTGATC.fastq/BW-Combo3-048_RA.fastq/' _RA_GGCGCTGATC.fastq
rename 's/_RA_GGCTAAGGTC.fastq/BW-Combo3-049_RA.fastq/' _RA_GGCTAAGGTC.fastq
rename 's/_RA_GGAGGCTAAC.fastq/BW-Combo3-050_RA.fastq/' _RA_GGAGGCTAAC.fastq
rename 's/_RA_GGTGGTGGTA.fastq/BW-Combo3-051_RA.fastq/' _RA_GGTGGTGGTA.fastq
rename 's/_RA_GGGGTGCGAA.fastq/BW-Combo3-052_RA.fastq/' _RA_GGGGTGCGAA.fastq
rename 's/_RA_GGCTCAATGA.fastq/BW-Combo3-053_RA.fastq/' _RA_GGCTCAATGA.fastq
rename 's/_RA_GGCAAGACTA.fastq/BW-Combo3-054_RA.fastq/' _RA_GGCAAGACTA.fastq
rename 's/_RA_GGACAGCAGA.fastq/BW-Combo3-055_RA.fastq/' _RA_GGACAGCAGA.fastq
rename 's/_RA_GGCAGATCTG.fastq/BW-Combo3-056_RA.fastq/' _RA_GGCAGATCTG.fastq
rename 's/_RA_GGGAACAGGC.fastq/BW-Combo3-057_RA.fastq/' _RA_GGGAACAGGC.fastq
rename 's/_RA_GGATAGCGAC.fastq/BW-Combo3-058_RA.fastq/' _RA_GGATAGCGAC.fastq
rename 's/_RA_GGTTCACGCA.fastq/BW-Combo3-059_RA.fastq/' _RA_GGTTCACGCA.fastq
rename 's/_RA_GGGTACGCAA.fastq/BW-Combo3-060_RA.fastq/' _RA_GGGTACGCAA.fastq
rename 's/_RA_GGCTGAGCCA.fastq/BW-Combo3-061_RA.fastq/' _RA_GGCTGAGCCA.fastq
rename 's/_RA_GGCAATGGAA.fastq/BW-Combo3-062_RA.fastq/' _RA_GGCAATGGAA.fastq
rename 's/_RA_GGACCTCCAA.fastq/BW-Combo3-063_RA.fastq/' _RA_GGACCTCCAA.fastq
rename 's/_RA_GGATGCCTAA.fastq/BW-Combo3-064_RA.fastq/' _RA_GGATGCCTAA.fastq
rename 's/_RA_GGGACAGTGC.fastq/BW-Combo3-065_RA.fastq/' _RA_GGGACAGTGC.fastq
rename 's/_RA_GGACGACAAG.fastq/BW-Combo3-066_RA.fastq/' _RA_GGACGACAAG.fastq
rename 's/_RA_GGACACGAGA.fastq/BW-Combo3-067_RA.fastq/' _RA_GGACACGAGA.fastq
rename 's/_RA_GGGTCGTAGA.fastq/BW-Combo3-068_RA.fastq/' _RA_GGGTCGTAGA.fastq
rename 's/_RA_GGCTGGCATA.fastq/BW-Combo3-069_RA.fastq/' _RA_GGCTGGCATA.fastq
rename 's/_RA_GGCACTTCGA.fastq/BW-Combo3-070_RA.fastq/' _RA_GGCACTTCGA.fastq
rename 's/_RA_GGACGCTCGA.fastq/BW-Combo3-071_RA.fastq/' _RA_GGACGCTCGA.fastq
rename 's/_RA_GGAACGAACG.fastq/BW-Combo3-072_RA.fastq/' _RA_GGAACGAACG.fastq
rename 's/_RA_GGGAGTTAGC.fastq/BW-Combo3-073_RA.fastq/' _RA_GGGAGTTAGC.fastq
rename 's/_RA_GGATTGGCTC.fastq/BW-Combo3-074_RA.fastq/' _RA_GGATTGGCTC.fastq
rename 's/_RA_GGAAGAGATC.fastq/BW-Combo3-075_RA.fastq/' _RA_GGAAGAGATC.fastq
rename 's/_RA_GGGTCTGTCA.fastq/BW-Combo3-076_RA.fastq/' _RA_GGGTCTGTCA.fastq
rename 's/_RA_GGGAATCTGA.fastq/BW-Combo3-077_RA.fastq/' _RA_GGGAATCTGA.fastq
rename 's/_RA_GGCAGCGTTA.fastq/BW-Combo3-078_RA.fastq/' _RA_GGCAGCGTTA.fastq
rename 's/_RA_GGACGTATCA.fastq/BW-Combo3-079_RA.fastq/' _RA_GGACGTATCA.fastq
rename 's/_RA_GGAGTACAAG.fastq/BW-Combo3-080_RA.fastq/' _RA_GGAGTACAAG.fastq
rename 's/_RA_GGGATGAATC.fastq/BW-Combo3-081_RA.fastq/' _RA_GGGATGAATC.fastq
rename 's/_RA_GGCAAGGAGC.fastq/BW-Combo3-082_RA.fastq/' _RA_GGCAAGGAGC.fastq
rename 's/_RA_GGAAGGACAC.fastq/BW-Combo3-083_RA.fastq/' _RA_GGAAGGACAC.fastq
rename 's/_RA_GGGTGTTCTA.fastq/BW-Combo3-084_RA.fastq/' _RA_GGGTGTTCTA.fastq
rename 's/_RA_GGGACTAGTA.fastq/BW-Combo3-085_RA.fastq/' _RA_GGGACTAGTA.fastq
rename 's/_RA_GGCATACCAA.fastq/BW-Combo3-086_RA.fastq/' _RA_GGCATACCAA.fastq
rename 's/_RA_GGACTATGCA.fastq/BW-Combo3-087_RA.fastq/' _RA_GGACTATGCA.fastq
rename 's/_RA_GGCATCAAGT.fastq/BW-Combo3-088_RA.fastq/' _RA_GGCATCAAGT.fastq
rename 's/_RA_GGGCCAAGAC.fastq/BW-Combo3-089_RA.fastq/' _RA_GGGCCAAGAC.fastq
rename 's/_RA_GGCACCTTAC.fastq/BW-Combo3-090_RA.fastq/' _RA_GGCACCTTAC.fastq
rename 's/_RA_GGAATCCGTC.fastq/BW-Combo3-091_RA.fastq/' _RA_GGAATCCGTC.fastq
rename 's/_RA_GGTAGGATGA.fastq/BW-Combo3-092_RA.fastq/' _RA_GGTAGGATGA.fastq
rename 's/_RA_GGGAGCTGAA.fastq/BW-Combo4-464_RA.fastq/' _RA_GGGAGCTGAA.fastq
rename 's/_RA_GGCCAGTTCA.fastq/BW-Combo4-465_RA.fastq/' _RA_GGCCAGTTCA.fastq
rename 's/_RA_GGAGAGTCAA.fastq/BW-Combo4-466_RA.fastq/' _RA_GGAGAGTCAA.fastq
rename 's/_RA_GGAGTGGTCA.fastq/BW-Combo4-467_RA.fastq/' _RA_GGAGTGGTCA.fastq
rename 's/_RB_GGCCATCCTC.fastq/BW-Combo3-001_RB.fastq/' _RB_GGCCATCCTC.fastq
rename 's/_RB_GGAATGTTGC.fastq/BW-Combo3-002_RB.fastq/' _RB_GGAATGTTGC.fastq
rename 's/_RB_GGTATCAGCA.fastq/BW-Combo3-003_RB.fastq/' _RB_GGTATCAGCA.fastq
rename 's/_RB_GGGATAGACA.fastq/BW-Combo3-004_RB.fastq/' _RB_GGGATAGACA.fastq
rename 's/_RB_GGCCGAAGTA.fastq/BW-Combo3-005_RB.fastq/' _RB_GGCCGAAGTA.fastq
rename 's/_RB_GGAGATCGCA.fastq/BW-Combo3-006_RB.fastq/' _RB_GGAGATCGCA.fastq
rename 's/_RB_GGAACAACCA.fastq/BW-Combo3-007_RB.fastq/' _RB_GGAACAACCA.fastq
rename 's/_RB_GGACAAGCTA.fastq/BW-Combo3-008_RB.fastq/' _RB_GGACAAGCTA.fastq
rename 's/_RB_GGCCGACAAC.fastq/BW-Combo3-009_RB.fastq/' _RB_GGCCGACAAC.fastq
rename 's/_RB_GGACACTGAC.fastq/BW-Combo3-010_RB.fastq/' _RB_GGACACTGAC.fastq
rename 's/_RB_GGTCCGTCTA.fastq/BW-Combo3-011_RB.fastq/' _RB_GGTCCGTCTA.fastq
rename 's/_RB_GGGCCACATA.fastq/BW-Combo3-012_RB.fastq/' _RB_GGGCCACATA.fastq
rename 's/_RB_GGCCGTGAGA.fastq/BW-Combo3-013_RB.fastq/' _RB_GGCCGTGAGA.fastq
rename 's/_RB_GGAGCAGGAA.fastq/BW-Combo3-014_RB.fastq/' _RB_GGAGCAGGAA.fastq
rename 's/_RB_GGAACCGAGA.fastq/BW-Combo3-015_RB.fastq/' _RB_GGAACCGAGA.fastq
rename 's/_RB_GGAAACATCG.fastq/BW-Combo3-016_RB.fastq/' _RB_GGAAACATCG.fastq
rename 's/_RB_GGAGTCAAGC.fastq/BW-Combo3-017_RB.fastq/' _RB_GGAGTCAAGC.fastq
rename 's/_RB_GGACAGATTC.fastq/BW-Combo3-018_RB.fastq/' _RB_GGACAGATTC.fastq
rename 's/_RB_GGTCTTCACA.fastq/BW-Combo3-019_RB.fastq/' _RB_GGTCTTCACA.fastq
rename 's/_RB_GGGCGAGTAA.fastq/BW-Combo3-020_RB.fastq/' _RB_GGGCGAGTAA.fastq
rename 's/_RB_GGCCTCCTGA.fastq/BW-Combo3-021_RB.fastq/' _RB_GGCCTCCTGA.fastq
rename 's/_RB_GGAGTCACTA.fastq/BW-Combo3-022_RB.fastq/' _RB_GGAGTCACTA.fastq
rename 's/_RB_GGAACGCTTA.fastq/BW-Combo3-023_RB.fastq/' _RB_GGAACGCTTA.fastq
rename 's/_RB_GGACATTGGC.fastq/BW-Combo3-024_RB.fastq/' _RB_GGACATTGGC.fastq
rename 's/_RB_GGCCTCTATC.fastq/BW-Combo3-025_RB.fastq/' _RB_GGCCTCTATC.fastq
rename 's/_RB_GGAGATGTAC.fastq/BW-Combo3-026_RB.fastq/' _RB_GGAGATGTAC.fastq
rename 's/_RB_GGTGAAGAGA.fastq/BW-Combo3-027_RB.fastq/' _RB_GGTGAAGAGA.fastq
rename 's/_RB_GGGCTAACGA.fastq/BW-Combo3-028_RB.fastq/' _RB_GGGCTAACGA.fastq
rename 's/_RB_GGCGAACTTA.fastq/BW-Combo3-029_RB.fastq/' _RB_GGCGAACTTA.fastq
rename 's/_RB_GGATCCTGTA.fastq/BW-Combo3-030_RB.fastq/' _RB_GGATCCTGTA.fastq
rename 's/_RB_GGAAGACGGA.fastq/BW-Combo3-031_RB.fastq/' _RB_GGAAGACGGA.fastq
rename 's/_RB_GGACCACTGT.fastq/BW-Combo3-032_RB.fastq/' _RB_GGACCACTGT.fastq
rename 's/_RB_GGCGACACAC.fastq/BW-Combo3-033_RB.fastq/' _RB_GGCGACACAC.fastq
rename 's/_RB_GGAGCACCTC.fastq/BW-Combo3-034_RB.fastq/' _RB_GGAGCACCTC.fastq
rename 's/_RB_GGTGGAACAA.fastq/BW-Combo3-035_RB.fastq/' _RB_GGTGGAACAA.fastq
rename 's/_RB_GGGCTCGGTA.fastq/BW-Combo3-036_RB.fastq/' _RB_GGGCTCGGTA.fastq
rename 's/_RB_GGCGACTGGA.fastq/BW-Combo3-037_RB.fastq/' _RB_GGCGACTGGA.fastq
rename 's/_RB_GGATTGAGGA.fastq/BW-Combo3-038_RB.fastq/' _RB_GGATTGAGGA.fastq
rename 's/_RB_GGAAGGTACA.fastq/BW-Combo3-039_RB.fastq/' _RB_GGAAGGTACA.fastq
rename 's/_RB_GGAACGTGAT.fastq/BW-Combo3-040_RB.fastq/' _RB_GGAACGTGAT.fastq
rename 's/_RB_GGCGGATTGC.fastq/BW-Combo3-041_RB.fastq/' _RB_GGCGGATTGC.fastq
rename 's/_RB_GGAGCCATGC.fastq/BW-Combo3-042_RB.fastq/' _RB_GGAGCCATGC.fastq
rename 's/_RB_GGTGGCTTCA.fastq/BW-Combo3-043_RB.fastq/' _RB_GGTGGCTTCA.fastq
rename 's/_RB_GGGGAGAACA.fastq/BW-Combo3-044_RB.fastq/' _RB_GGGGAGAACA.fastq
rename 's/_RB_GGCGCATACA.fastq/BW-Combo3-045_RB.fastq/' _RB_GGCGCATACA.fastq
rename 's/_RB_GGCAACCACA.fastq/BW-Combo3-046_RB.fastq/' _RB_GGCAACCACA.fastq
rename 's/_RB_GGACACAGAA.fastq/BW-Combo3-047_RB.fastq/' _RB_GGACACAGAA.fastq
rename 's/_RB_GGCGCTGATC.fastq/BW-Combo3-048_RB.fastq/' _RB_GGCGCTGATC.fastq
rename 's/_RB_GGCTAAGGTC.fastq/BW-Combo3-049_RB.fastq/' _RB_GGCTAAGGTC.fastq
rename 's/_RB_GGAGGCTAAC.fastq/BW-Combo3-050_RB.fastq/' _RB_GGAGGCTAAC.fastq
rename 's/_RB_GGTGGTGGTA.fastq/BW-Combo3-051_RB.fastq/' _RB_GGTGGTGGTA.fastq
rename 's/_RB_GGGGTGCGAA.fastq/BW-Combo3-052_RB.fastq/' _RB_GGGGTGCGAA.fastq
rename 's/_RB_GGCTCAATGA.fastq/BW-Combo3-053_RB.fastq/' _RB_GGCTCAATGA.fastq
rename 's/_RB_GGCAAGACTA.fastq/BW-Combo3-054_RB.fastq/' _RB_GGCAAGACTA.fastq
rename 's/_RB_GGACAGCAGA.fastq/BW-Combo3-055_RB.fastq/' _RB_GGACAGCAGA.fastq
rename 's/_RB_GGCAGATCTG.fastq/BW-Combo3-056_RB.fastq/' _RB_GGCAGATCTG.fastq
rename 's/_RB_GGGAACAGGC.fastq/BW-Combo3-057_RB.fastq/' _RB_GGGAACAGGC.fastq
rename 's/_RB_GGATAGCGAC.fastq/BW-Combo3-058_RB.fastq/' _RB_GGATAGCGAC.fastq
rename 's/_RB_GGTTCACGCA.fastq/BW-Combo3-059_RB.fastq/' _RB_GGTTCACGCA.fastq
rename 's/_RB_GGGTACGCAA.fastq/BW-Combo3-060_RB.fastq/' _RB_GGGTACGCAA.fastq
rename 's/_RB_GGCTGAGCCA.fastq/BW-Combo3-061_RB.fastq/' _RB_GGCTGAGCCA.fastq
rename 's/_RB_GGCAATGGAA.fastq/BW-Combo3-062_RB.fastq/' _RB_GGCAATGGAA.fastq
rename 's/_RB_GGACCTCCAA.fastq/BW-Combo3-063_RB.fastq/' _RB_GGACCTCCAA.fastq
rename 's/_RB_GGATGCCTAA.fastq/BW-Combo3-064_RB.fastq/' _RB_GGATGCCTAA.fastq
rename 's/_RB_GGGACAGTGC.fastq/BW-Combo3-065_RB.fastq/' _RB_GGGACAGTGC.fastq
rename 's/_RB_GGACGACAAG.fastq/BW-Combo3-066_RB.fastq/' _RB_GGACGACAAG.fastq
rename 's/_RB_GGACACGAGA.fastq/BW-Combo3-067_RB.fastq/' _RB_GGACACGAGA.fastq
rename 's/_RB_GGGTCGTAGA.fastq/BW-Combo3-068_RB.fastq/' _RB_GGGTCGTAGA.fastq
rename 's/_RB_GGCTGGCATA.fastq/BW-Combo3-069_RB.fastq/' _RB_GGCTGGCATA.fastq
rename 's/_RB_GGCACTTCGA.fastq/BW-Combo3-070_RB.fastq/' _RB_GGCACTTCGA.fastq
rename 's/_RB_GGACGCTCGA.fastq/BW-Combo3-071_RB.fastq/' _RB_GGACGCTCGA.fastq
rename 's/_RB_GGAACGAACG.fastq/BW-Combo3-072_RB.fastq/' _RB_GGAACGAACG.fastq
rename 's/_RB_GGGAGTTAGC.fastq/BW-Combo3-073_RB.fastq/' _RB_GGGAGTTAGC.fastq
rename 's/_RB_GGATTGGCTC.fastq/BW-Combo3-074_RB.fastq/' _RB_GGATTGGCTC.fastq
rename 's/_RB_GGAAGAGATC.fastq/BW-Combo3-075_RB.fastq/' _RB_GGAAGAGATC.fastq
rename 's/_RB_GGGTCTGTCA.fastq/BW-Combo3-076_RB.fastq/' _RB_GGGTCTGTCA.fastq
rename 's/_RB_GGGAATCTGA.fastq/BW-Combo3-077_RB.fastq/' _RB_GGGAATCTGA.fastq
rename 's/_RB_GGCAGCGTTA.fastq/BW-Combo3-078_RB.fastq/' _RB_GGCAGCGTTA.fastq
rename 's/_RB_GGACGTATCA.fastq/BW-Combo3-079_RB.fastq/' _RB_GGACGTATCA.fastq
rename 's/_RB_GGAGTACAAG.fastq/BW-Combo3-080_RB.fastq/' _RB_GGAGTACAAG.fastq
rename 's/_RB_GGGATGAATC.fastq/BW-Combo3-081_RB.fastq/' _RB_GGGATGAATC.fastq
rename 's/_RB_GGCAAGGAGC.fastq/BW-Combo3-082_RB.fastq/' _RB_GGCAAGGAGC.fastq
rename 's/_RB_GGAAGGACAC.fastq/BW-Combo3-083_RB.fastq/' _RB_GGAAGGACAC.fastq
rename 's/_RB_GGGTGTTCTA.fastq/BW-Combo3-084_RB.fastq/' _RB_GGGTGTTCTA.fastq
rename 's/_RB_GGGACTAGTA.fastq/BW-Combo3-085_RB.fastq/' _RB_GGGACTAGTA.fastq
rename 's/_RB_GGCATACCAA.fastq/BW-Combo3-086_RB.fastq/' _RB_GGCATACCAA.fastq
rename 's/_RB_GGACTATGCA.fastq/BW-Combo3-087_RB.fastq/' _RB_GGACTATGCA.fastq
rename 's/_RB_GGCATCAAGT.fastq/BW-Combo3-088_RB.fastq/' _RB_GGCATCAAGT.fastq
rename 's/_RB_GGGCCAAGAC.fastq/BW-Combo3-089_RB.fastq/' _RB_GGGCCAAGAC.fastq
rename 's/_RB_GGCACCTTAC.fastq/BW-Combo3-090_RB.fastq/' _RB_GGCACCTTAC.fastq
rename 's/_RB_GGAATCCGTC.fastq/BW-Combo3-091_RB.fastq/' _RB_GGAATCCGTC.fastq
rename 's/_RB_GGTAGGATGA.fastq/BW-Combo3-092_RB.fastq/' _RB_GGTAGGATGA.fastq
rename 's/_RB_GGGAGCTGAA.fastq/BW-Combo4-464_RB.fastq/' _RB_GGGAGCTGAA.fastq
rename 's/_RB_GGCCAGTTCA.fastq/BW-Combo4-465_RB.fastq/' _RB_GGCCAGTTCA.fastq
rename 's/_RB_GGAGAGTCAA.fastq/BW-Combo4-466_RB.fastq/' _RB_GGAGAGTCAA.fastq
rename 's/_RB_GGAGTGGTCA.fastq/BW-Combo4-467_RB.fastq/' _RB_GGAGTGGTCA.fastq
