rename 's/_RA_GGCCATCCTC.fastq/BW-Combo2-097_RA.fastq/' _RA_GGCCATCCTC.fastq
rename 's/_RA_GGAATGTTGC.fastq/BW-Combo2-098_RA.fastq/' _RA_GGAATGTTGC.fastq
rename 's/_RA_GGTATCAGCA.fastq/BW-Combo2-099_RA.fastq/' _RA_GGTATCAGCA.fastq
rename 's/_RA_GGGATAGACA.fastq/BW-Combo2-100_RA.fastq/' _RA_GGGATAGACA.fastq
rename 's/_RA_GGCCGAAGTA.fastq/BW-Combo2-101_RA.fastq/' _RA_GGCCGAAGTA.fastq
rename 's/_RA_GGAGATCGCA.fastq/BW-Combo2-102_RA.fastq/' _RA_GGAGATCGCA.fastq
rename 's/_RA_GGAACAACCA.fastq/BW-Combo2-103_RA.fastq/' _RA_GGAACAACCA.fastq
rename 's/_RA_GGACAAGCTA.fastq/BW-Combo2-104_RA.fastq/' _RA_GGACAAGCTA.fastq
rename 's/_RA_GGCCGACAAC.fastq/BW-Combo2-105_RA.fastq/' _RA_GGCCGACAAC.fastq
rename 's/_RA_GGACACTGAC.fastq/BW-Combo2-106_RA.fastq/' _RA_GGACACTGAC.fastq
rename 's/_RA_GGTCCGTCTA.fastq/BW-Combo2-107_RA.fastq/' _RA_GGTCCGTCTA.fastq
rename 's/_RA_GGGCCACATA.fastq/BW-Combo2-108_RA.fastq/' _RA_GGGCCACATA.fastq
rename 's/_RA_GGCCGTGAGA.fastq/BW-Combo2-109_RA.fastq/' _RA_GGCCGTGAGA.fastq
rename 's/_RA_GGAGCAGGAA.fastq/BW-Combo2-110_RA.fastq/' _RA_GGAGCAGGAA.fastq
rename 's/_RA_GGAACCGAGA.fastq/BW-Combo2-111_RA.fastq/' _RA_GGAACCGAGA.fastq
rename 's/_RA_GGAAACATCG.fastq/BW-Combo2-112_RA.fastq/' _RA_GGAAACATCG.fastq
rename 's/_RA_GGAGTCAAGC.fastq/BW-Combo2-113_RA.fastq/' _RA_GGAGTCAAGC.fastq
rename 's/_RA_GGACAGATTC.fastq/BW-Combo2-114_RA.fastq/' _RA_GGACAGATTC.fastq
rename 's/_RA_GGTCTTCACA.fastq/BW-Combo2-115_RA.fastq/' _RA_GGTCTTCACA.fastq
rename 's/_RA_GGGCGAGTAA.fastq/BW-Combo2-116_RA.fastq/' _RA_GGGCGAGTAA.fastq
rename 's/_RA_GGCCTCCTGA.fastq/BW-Combo2-117_RA.fastq/' _RA_GGCCTCCTGA.fastq
rename 's/_RA_GGAGTCACTA.fastq/BW-Combo2-118_RA.fastq/' _RA_GGAGTCACTA.fastq
rename 's/_RA_GGAACGCTTA.fastq/BW-Combo2-119_RA.fastq/' _RA_GGAACGCTTA.fastq
rename 's/_RA_GGACATTGGC.fastq/BW-Combo2-120_RA.fastq/' _RA_GGACATTGGC.fastq
rename 's/_RA_GGCCTCTATC.fastq/BW-Combo2-121_RA.fastq/' _RA_GGCCTCTATC.fastq
rename 's/_RA_GGAGATGTAC.fastq/BW-Combo2-122_RA.fastq/' _RA_GGAGATGTAC.fastq
rename 's/_RA_GGTGAAGAGA.fastq/BW-Combo2-123_RA.fastq/' _RA_GGTGAAGAGA.fastq
rename 's/_RA_GGGCTAACGA.fastq/BW-Combo2-124_RA.fastq/' _RA_GGGCTAACGA.fastq
rename 's/_RA_GGCGAACTTA.fastq/BW-Combo2-125_RA.fastq/' _RA_GGCGAACTTA.fastq
rename 's/_RA_GGATCCTGTA.fastq/BW-Combo2-126_RA.fastq/' _RA_GGATCCTGTA.fastq
rename 's/_RA_GGAAGACGGA.fastq/BW-Combo2-127_RA.fastq/' _RA_GGAAGACGGA.fastq
rename 's/_RA_GGACCACTGT.fastq/BW-Combo2-128_RA.fastq/' _RA_GGACCACTGT.fastq
rename 's/_RA_GGCGACACAC.fastq/BW-Combo2-129_RA.fastq/' _RA_GGCGACACAC.fastq
rename 's/_RA_GGAGCACCTC.fastq/BW-Combo2-130_RA.fastq/' _RA_GGAGCACCTC.fastq
rename 's/_RA_GGTGGAACAA.fastq/BW-Combo2-131_RA.fastq/' _RA_GGTGGAACAA.fastq
rename 's/_RA_GGGCTCGGTA.fastq/BW-Combo2-132_RA.fastq/' _RA_GGGCTCGGTA.fastq
rename 's/_RA_GGCGACTGGA.fastq/BW-Combo2-133_RA.fastq/' _RA_GGCGACTGGA.fastq
rename 's/_RA_GGATTGAGGA.fastq/BW-Combo2-134_RA.fastq/' _RA_GGATTGAGGA.fastq
rename 's/_RA_GGAAGGTACA.fastq/BW-Combo2-135_RA.fastq/' _RA_GGAAGGTACA.fastq
rename 's/_RA_GGAACGTGAT.fastq/BW-Combo2-136_RA.fastq/' _RA_GGAACGTGAT.fastq
rename 's/_RA_GGCGGATTGC.fastq/BW-Combo2-137_RA.fastq/' _RA_GGCGGATTGC.fastq
rename 's/_RA_GGAGCCATGC.fastq/BW-Combo2-138_RA.fastq/' _RA_GGAGCCATGC.fastq
rename 's/_RA_GGTGGCTTCA.fastq/BW-Combo2-139_RA.fastq/' _RA_GGTGGCTTCA.fastq
rename 's/_RA_GGGGAGAACA.fastq/BW-Combo2-140_RA.fastq/' _RA_GGGGAGAACA.fastq
rename 's/_RA_GGCGCATACA.fastq/BW-Combo2-141_RA.fastq/' _RA_GGCGCATACA.fastq
rename 's/_RA_GGCAACCACA.fastq/BW-Combo2-142_RA.fastq/' _RA_GGCAACCACA.fastq
rename 's/_RA_GGACACAGAA.fastq/BW-Combo2-143_RA.fastq/' _RA_GGACACAGAA.fastq
rename 's/_RA_GGCGCTGATC.fastq/BW-Combo2-144_RA.fastq/' _RA_GGCGCTGATC.fastq
rename 's/_RA_GGCTAAGGTC.fastq/BW-Combo2-145_RA.fastq/' _RA_GGCTAAGGTC.fastq
rename 's/_RA_GGAGGCTAAC.fastq/BW-Combo2-146_RA.fastq/' _RA_GGAGGCTAAC.fastq
rename 's/_RA_GGTGGTGGTA.fastq/BW-Combo2-147_RA.fastq/' _RA_GGTGGTGGTA.fastq
rename 's/_RA_GGGGTGCGAA.fastq/BW-Combo2-148_RA.fastq/' _RA_GGGGTGCGAA.fastq
rename 's/_RA_GGCTCAATGA.fastq/BW-Combo2-149_RA.fastq/' _RA_GGCTCAATGA.fastq
rename 's/_RA_GGCAAGACTA.fastq/BW-Combo2-150_RA.fastq/' _RA_GGCAAGACTA.fastq
rename 's/_RA_GGACAGCAGA.fastq/BW-Combo2-151_RA.fastq/' _RA_GGACAGCAGA.fastq
rename 's/_RA_GGCAGATCTG.fastq/BW-Combo2-152_RA.fastq/' _RA_GGCAGATCTG.fastq
rename 's/_RA_GGGAACAGGC.fastq/BW-Combo2-153_RA.fastq/' _RA_GGGAACAGGC.fastq
rename 's/_RA_GGATAGCGAC.fastq/BW-Combo2-154_RA.fastq/' _RA_GGATAGCGAC.fastq
rename 's/_RA_GGTTCACGCA.fastq/BW-Combo2-155_RA.fastq/' _RA_GGTTCACGCA.fastq
rename 's/_RA_GGGTACGCAA.fastq/BW-Combo2-156_RA.fastq/' _RA_GGGTACGCAA.fastq
rename 's/_RA_GGCTGAGCCA.fastq/BW-Combo2-157_RA.fastq/' _RA_GGCTGAGCCA.fastq
rename 's/_RA_GGCAATGGAA.fastq/BW-Combo2-158_RA.fastq/' _RA_GGCAATGGAA.fastq
rename 's/_RA_GGACCTCCAA.fastq/BW-Combo2-159_RA.fastq/' _RA_GGACCTCCAA.fastq
rename 's/_RA_GGATGCCTAA.fastq/BW-Combo2-160_RA.fastq/' _RA_GGATGCCTAA.fastq
rename 's/_RA_GGGACAGTGC.fastq/BW-Combo2-161_RA.fastq/' _RA_GGGACAGTGC.fastq
rename 's/_RA_GGACGACAAG.fastq/BW-Combo2-162_RA.fastq/' _RA_GGACGACAAG.fastq
rename 's/_RA_GGACACGAGA.fastq/BW-Combo2-163_RA.fastq/' _RA_GGACACGAGA.fastq
rename 's/_RA_GGGTCGTAGA.fastq/BW-Combo2-164_RA.fastq/' _RA_GGGTCGTAGA.fastq
rename 's/_RA_GGCTGGCATA.fastq/BW-Combo2-165_RA.fastq/' _RA_GGCTGGCATA.fastq
rename 's/_RA_GGCACTTCGA.fastq/BW-Combo2-166_RA.fastq/' _RA_GGCACTTCGA.fastq
rename 's/_RA_GGACGCTCGA.fastq/BW-Combo2-167_RA.fastq/' _RA_GGACGCTCGA.fastq
rename 's/_RA_GGAACGAACG.fastq/BW-Combo2-168_RA.fastq/' _RA_GGAACGAACG.fastq
rename 's/_RA_GGGAGTTAGC.fastq/BW-Combo2-169_RA.fastq/' _RA_GGGAGTTAGC.fastq
rename 's/_RA_GGATTGGCTC.fastq/BW-Combo2-170_RA.fastq/' _RA_GGATTGGCTC.fastq
rename 's/_RA_GGAAGAGATC.fastq/BW-Combo2-171_RA.fastq/' _RA_GGAAGAGATC.fastq
rename 's/_RA_GGGTCTGTCA.fastq/BW-Combo2-172_RA.fastq/' _RA_GGGTCTGTCA.fastq
rename 's/_RA_GGGAATCTGA.fastq/BW-Combo2-173_RA.fastq/' _RA_GGGAATCTGA.fastq
rename 's/_RA_GGCAGCGTTA.fastq/BW-Combo2-174_RA.fastq/' _RA_GGCAGCGTTA.fastq
rename 's/_RA_GGACGTATCA.fastq/BW-Combo2-175_RA.fastq/' _RA_GGACGTATCA.fastq
rename 's/_RA_GGAGTACAAG.fastq/BW-Combo2-176_RA.fastq/' _RA_GGAGTACAAG.fastq
rename 's/_RA_GGGATGAATC.fastq/BW-Combo2-177_RA.fastq/' _RA_GGGATGAATC.fastq
rename 's/_RA_GGCAAGGAGC.fastq/BW-Combo2-178_RA.fastq/' _RA_GGCAAGGAGC.fastq
rename 's/_RA_GGAAGGACAC.fastq/BW-Combo2-179_RA.fastq/' _RA_GGAAGGACAC.fastq
rename 's/_RA_GGGTGTTCTA.fastq/BW-Combo2-180_RA.fastq/' _RA_GGGTGTTCTA.fastq
rename 's/_RA_GGGACTAGTA.fastq/BW-Combo2-181_RA.fastq/' _RA_GGGACTAGTA.fastq
rename 's/_RA_GGCATACCAA.fastq/BW-Combo2-182_RA.fastq/' _RA_GGCATACCAA.fastq
rename 's/_RA_GGACTATGCA.fastq/BW-Combo2-183_RA.fastq/' _RA_GGACTATGCA.fastq
rename 's/_RA_GGCATCAAGT.fastq/BW-Combo2-184_RA.fastq/' _RA_GGCATCAAGT.fastq
rename 's/_RA_GGGCCAAGAC.fastq/BW-Combo2-185_RA.fastq/' _RA_GGGCCAAGAC.fastq
rename 's/_RA_GGCACCTTAC.fastq/BW-Combo2-186_RA.fastq/' _RA_GGCACCTTAC.fastq
rename 's/_RA_GGAATCCGTC.fastq/BW-Combo2-187_RA.fastq/' _RA_GGAATCCGTC.fastq
rename 's/_RA_GGTAGGATGA.fastq/BW-Combo2-188_RA.fastq/' _RA_GGTAGGATGA.fastq
rename 's/_RA_GGGAGCTGAA.fastq/BW-Combo2-189_RA.fastq/' _RA_GGGAGCTGAA.fastq
rename 's/_RA_GGCCAGTTCA.fastq/BW-Combo2-190_RA.fastq/' _RA_GGCCAGTTCA.fastq
rename 's/_RA_GGAGAGTCAA.fastq/BW-Combo2-191_RA.fastq/' _RA_GGAGAGTCAA.fastq
rename 's/_RA_GGAGTGGTCA.fastq/BW-Combo2-192_RA.fastq/' _RA_GGAGTGGTCA.fastq
rename 's/_RB_GGCCATCCTC.fastq/BW-Combo2-097_RB.fastq/' _RB_GGCCATCCTC.fastq
rename 's/_RB_GGAATGTTGC.fastq/BW-Combo2-098_RB.fastq/' _RB_GGAATGTTGC.fastq
rename 's/_RB_GGTATCAGCA.fastq/BW-Combo2-099_RB.fastq/' _RB_GGTATCAGCA.fastq
rename 's/_RB_GGGATAGACA.fastq/BW-Combo2-100_RB.fastq/' _RB_GGGATAGACA.fastq
rename 's/_RB_GGCCGAAGTA.fastq/BW-Combo2-101_RB.fastq/' _RB_GGCCGAAGTA.fastq
rename 's/_RB_GGAGATCGCA.fastq/BW-Combo2-102_RB.fastq/' _RB_GGAGATCGCA.fastq
rename 's/_RB_GGAACAACCA.fastq/BW-Combo2-103_RB.fastq/' _RB_GGAACAACCA.fastq
rename 's/_RB_GGACAAGCTA.fastq/BW-Combo2-104_RB.fastq/' _RB_GGACAAGCTA.fastq
rename 's/_RB_GGCCGACAAC.fastq/BW-Combo2-105_RB.fastq/' _RB_GGCCGACAAC.fastq
rename 's/_RB_GGACACTGAC.fastq/BW-Combo2-106_RB.fastq/' _RB_GGACACTGAC.fastq
rename 's/_RB_GGTCCGTCTA.fastq/BW-Combo2-107_RB.fastq/' _RB_GGTCCGTCTA.fastq
rename 's/_RB_GGGCCACATA.fastq/BW-Combo2-108_RB.fastq/' _RB_GGGCCACATA.fastq
rename 's/_RB_GGCCGTGAGA.fastq/BW-Combo2-109_RB.fastq/' _RB_GGCCGTGAGA.fastq
rename 's/_RB_GGAGCAGGAA.fastq/BW-Combo2-110_RB.fastq/' _RB_GGAGCAGGAA.fastq
rename 's/_RB_GGAACCGAGA.fastq/BW-Combo2-111_RB.fastq/' _RB_GGAACCGAGA.fastq
rename 's/_RB_GGAAACATCG.fastq/BW-Combo2-112_RB.fastq/' _RB_GGAAACATCG.fastq
rename 's/_RB_GGAGTCAAGC.fastq/BW-Combo2-113_RB.fastq/' _RB_GGAGTCAAGC.fastq
rename 's/_RB_GGACAGATTC.fastq/BW-Combo2-114_RB.fastq/' _RB_GGACAGATTC.fastq
rename 's/_RB_GGTCTTCACA.fastq/BW-Combo2-115_RB.fastq/' _RB_GGTCTTCACA.fastq
rename 's/_RB_GGGCGAGTAA.fastq/BW-Combo2-116_RB.fastq/' _RB_GGGCGAGTAA.fastq
rename 's/_RB_GGCCTCCTGA.fastq/BW-Combo2-117_RB.fastq/' _RB_GGCCTCCTGA.fastq
rename 's/_RB_GGAGTCACTA.fastq/BW-Combo2-118_RB.fastq/' _RB_GGAGTCACTA.fastq
rename 's/_RB_GGAACGCTTA.fastq/BW-Combo2-119_RB.fastq/' _RB_GGAACGCTTA.fastq
rename 's/_RB_GGACATTGGC.fastq/BW-Combo2-120_RB.fastq/' _RB_GGACATTGGC.fastq
rename 's/_RB_GGCCTCTATC.fastq/BW-Combo2-121_RB.fastq/' _RB_GGCCTCTATC.fastq
rename 's/_RB_GGAGATGTAC.fastq/BW-Combo2-122_RB.fastq/' _RB_GGAGATGTAC.fastq
rename 's/_RB_GGTGAAGAGA.fastq/BW-Combo2-123_RB.fastq/' _RB_GGTGAAGAGA.fastq
rename 's/_RB_GGGCTAACGA.fastq/BW-Combo2-124_RB.fastq/' _RB_GGGCTAACGA.fastq
rename 's/_RB_GGCGAACTTA.fastq/BW-Combo2-125_RB.fastq/' _RB_GGCGAACTTA.fastq
rename 's/_RB_GGATCCTGTA.fastq/BW-Combo2-126_RB.fastq/' _RB_GGATCCTGTA.fastq
rename 's/_RB_GGAAGACGGA.fastq/BW-Combo2-127_RB.fastq/' _RB_GGAAGACGGA.fastq
rename 's/_RB_GGACCACTGT.fastq/BW-Combo2-128_RB.fastq/' _RB_GGACCACTGT.fastq
rename 's/_RB_GGCGACACAC.fastq/BW-Combo2-129_RB.fastq/' _RB_GGCGACACAC.fastq
rename 's/_RB_GGAGCACCTC.fastq/BW-Combo2-130_RB.fastq/' _RB_GGAGCACCTC.fastq
rename 's/_RB_GGTGGAACAA.fastq/BW-Combo2-131_RB.fastq/' _RB_GGTGGAACAA.fastq
rename 's/_RB_GGGCTCGGTA.fastq/BW-Combo2-132_RB.fastq/' _RB_GGGCTCGGTA.fastq
rename 's/_RB_GGCGACTGGA.fastq/BW-Combo2-133_RB.fastq/' _RB_GGCGACTGGA.fastq
rename 's/_RB_GGATTGAGGA.fastq/BW-Combo2-134_RB.fastq/' _RB_GGATTGAGGA.fastq
rename 's/_RB_GGAAGGTACA.fastq/BW-Combo2-135_RB.fastq/' _RB_GGAAGGTACA.fastq
rename 's/_RB_GGAACGTGAT.fastq/BW-Combo2-136_RB.fastq/' _RB_GGAACGTGAT.fastq
rename 's/_RB_GGCGGATTGC.fastq/BW-Combo2-137_RB.fastq/' _RB_GGCGGATTGC.fastq
rename 's/_RB_GGAGCCATGC.fastq/BW-Combo2-138_RB.fastq/' _RB_GGAGCCATGC.fastq
rename 's/_RB_GGTGGCTTCA.fastq/BW-Combo2-139_RB.fastq/' _RB_GGTGGCTTCA.fastq
rename 's/_RB_GGGGAGAACA.fastq/BW-Combo2-140_RB.fastq/' _RB_GGGGAGAACA.fastq
rename 's/_RB_GGCGCATACA.fastq/BW-Combo2-141_RB.fastq/' _RB_GGCGCATACA.fastq
rename 's/_RB_GGCAACCACA.fastq/BW-Combo2-142_RB.fastq/' _RB_GGCAACCACA.fastq
rename 's/_RB_GGACACAGAA.fastq/BW-Combo2-143_RB.fastq/' _RB_GGACACAGAA.fastq
rename 's/_RB_GGCGCTGATC.fastq/BW-Combo2-144_RB.fastq/' _RB_GGCGCTGATC.fastq
rename 's/_RB_GGCTAAGGTC.fastq/BW-Combo2-145_RB.fastq/' _RB_GGCTAAGGTC.fastq
rename 's/_RB_GGAGGCTAAC.fastq/BW-Combo2-146_RB.fastq/' _RB_GGAGGCTAAC.fastq
rename 's/_RB_GGTGGTGGTA.fastq/BW-Combo2-147_RB.fastq/' _RB_GGTGGTGGTA.fastq
rename 's/_RB_GGGGTGCGAA.fastq/BW-Combo2-148_RB.fastq/' _RB_GGGGTGCGAA.fastq
rename 's/_RB_GGCTCAATGA.fastq/BW-Combo2-149_RB.fastq/' _RB_GGCTCAATGA.fastq
rename 's/_RB_GGCAAGACTA.fastq/BW-Combo2-150_RB.fastq/' _RB_GGCAAGACTA.fastq
rename 's/_RB_GGACAGCAGA.fastq/BW-Combo2-151_RB.fastq/' _RB_GGACAGCAGA.fastq
rename 's/_RB_GGCAGATCTG.fastq/BW-Combo2-152_RB.fastq/' _RB_GGCAGATCTG.fastq
rename 's/_RB_GGGAACAGGC.fastq/BW-Combo2-153_RB.fastq/' _RB_GGGAACAGGC.fastq
rename 's/_RB_GGATAGCGAC.fastq/BW-Combo2-154_RB.fastq/' _RB_GGATAGCGAC.fastq
rename 's/_RB_GGTTCACGCA.fastq/BW-Combo2-155_RB.fastq/' _RB_GGTTCACGCA.fastq
rename 's/_RB_GGGTACGCAA.fastq/BW-Combo2-156_RB.fastq/' _RB_GGGTACGCAA.fastq
rename 's/_RB_GGCTGAGCCA.fastq/BW-Combo2-157_RB.fastq/' _RB_GGCTGAGCCA.fastq
rename 's/_RB_GGCAATGGAA.fastq/BW-Combo2-158_RB.fastq/' _RB_GGCAATGGAA.fastq
rename 's/_RB_GGACCTCCAA.fastq/BW-Combo2-159_RB.fastq/' _RB_GGACCTCCAA.fastq
rename 's/_RB_GGATGCCTAA.fastq/BW-Combo2-160_RB.fastq/' _RB_GGATGCCTAA.fastq
rename 's/_RB_GGGACAGTGC.fastq/BW-Combo2-161_RB.fastq/' _RB_GGGACAGTGC.fastq
rename 's/_RB_GGACGACAAG.fastq/BW-Combo2-162_RB.fastq/' _RB_GGACGACAAG.fastq
rename 's/_RB_GGACACGAGA.fastq/BW-Combo2-163_RB.fastq/' _RB_GGACACGAGA.fastq
rename 's/_RB_GGGTCGTAGA.fastq/BW-Combo2-164_RB.fastq/' _RB_GGGTCGTAGA.fastq
rename 's/_RB_GGCTGGCATA.fastq/BW-Combo2-165_RB.fastq/' _RB_GGCTGGCATA.fastq
rename 's/_RB_GGCACTTCGA.fastq/BW-Combo2-166_RB.fastq/' _RB_GGCACTTCGA.fastq
rename 's/_RB_GGACGCTCGA.fastq/BW-Combo2-167_RB.fastq/' _RB_GGACGCTCGA.fastq
rename 's/_RB_GGAACGAACG.fastq/BW-Combo2-168_RB.fastq/' _RB_GGAACGAACG.fastq
rename 's/_RB_GGGAGTTAGC.fastq/BW-Combo2-169_RB.fastq/' _RB_GGGAGTTAGC.fastq
rename 's/_RB_GGATTGGCTC.fastq/BW-Combo2-170_RB.fastq/' _RB_GGATTGGCTC.fastq
rename 's/_RB_GGAAGAGATC.fastq/BW-Combo2-171_RB.fastq/' _RB_GGAAGAGATC.fastq
rename 's/_RB_GGGTCTGTCA.fastq/BW-Combo2-172_RB.fastq/' _RB_GGGTCTGTCA.fastq
rename 's/_RB_GGGAATCTGA.fastq/BW-Combo2-173_RB.fastq/' _RB_GGGAATCTGA.fastq
rename 's/_RB_GGCAGCGTTA.fastq/BW-Combo2-174_RB.fastq/' _RB_GGCAGCGTTA.fastq
rename 's/_RB_GGACGTATCA.fastq/BW-Combo2-175_RB.fastq/' _RB_GGACGTATCA.fastq
rename 's/_RB_GGAGTACAAG.fastq/BW-Combo2-176_RB.fastq/' _RB_GGAGTACAAG.fastq
rename 's/_RB_GGGATGAATC.fastq/BW-Combo2-177_RB.fastq/' _RB_GGGATGAATC.fastq
rename 's/_RB_GGCAAGGAGC.fastq/BW-Combo2-178_RB.fastq/' _RB_GGCAAGGAGC.fastq
rename 's/_RB_GGAAGGACAC.fastq/BW-Combo2-179_RB.fastq/' _RB_GGAAGGACAC.fastq
rename 's/_RB_GGGTGTTCTA.fastq/BW-Combo2-180_RB.fastq/' _RB_GGGTGTTCTA.fastq
rename 's/_RB_GGGACTAGTA.fastq/BW-Combo2-181_RB.fastq/' _RB_GGGACTAGTA.fastq
rename 's/_RB_GGCATACCAA.fastq/BW-Combo2-182_RB.fastq/' _RB_GGCATACCAA.fastq
rename 's/_RB_GGACTATGCA.fastq/BW-Combo2-183_RB.fastq/' _RB_GGACTATGCA.fastq
rename 's/_RB_GGCATCAAGT.fastq/BW-Combo2-184_RB.fastq/' _RB_GGCATCAAGT.fastq
rename 's/_RB_GGGCCAAGAC.fastq/BW-Combo2-185_RB.fastq/' _RB_GGGCCAAGAC.fastq
rename 's/_RB_GGCACCTTAC.fastq/BW-Combo2-186_RB.fastq/' _RB_GGCACCTTAC.fastq
rename 's/_RB_GGAATCCGTC.fastq/BW-Combo2-187_RB.fastq/' _RB_GGAATCCGTC.fastq
rename 's/_RB_GGTAGGATGA.fastq/BW-Combo2-188_RB.fastq/' _RB_GGTAGGATGA.fastq
rename 's/_RB_GGGAGCTGAA.fastq/BW-Combo2-189_RB.fastq/' _RB_GGGAGCTGAA.fastq
rename 's/_RB_GGCCAGTTCA.fastq/BW-Combo2-190_RB.fastq/' _RB_GGCCAGTTCA.fastq
rename 's/_RB_GGAGAGTCAA.fastq/BW-Combo2-191_RB.fastq/' _RB_GGAGAGTCAA.fastq
rename 's/_RB_GGAGTGGTCA.fastq/BW-Combo2-192_RB.fastq/' _RB_GGAGTGGTCA.fastq
