rename 's/_RA_GGCCATCCTC.fastq/BW-Combo3-193_RA.fastq/' _RA_GGCCATCCTC.fastq
rename 's/_RA_GGAATGTTGC.fastq/BW-Combo3-194_RA.fastq/' _RA_GGAATGTTGC.fastq
rename 's/_RA_GGTATCAGCA.fastq/BW-Combo3-195_RA.fastq/' _RA_GGTATCAGCA.fastq
rename 's/_RA_GGGATAGACA.fastq/BW-Combo3-196_RA.fastq/' _RA_GGGATAGACA.fastq
rename 's/_RA_GGCCGAAGTA.fastq/BW-Combo3-197_RA.fastq/' _RA_GGCCGAAGTA.fastq
rename 's/_RA_GGAGATCGCA.fastq/BW-Combo3-198_RA.fastq/' _RA_GGAGATCGCA.fastq
rename 's/_RA_GGAACAACCA.fastq/BW-Combo3-199_RA.fastq/' _RA_GGAACAACCA.fastq
rename 's/_RA_GGACAAGCTA.fastq/BW-Combo3-200_RA.fastq/' _RA_GGACAAGCTA.fastq
rename 's/_RA_GGCCGACAAC.fastq/BW-Combo3-201_RA.fastq/' _RA_GGCCGACAAC.fastq
rename 's/_RA_GGACACTGAC.fastq/BW-Combo3-202_RA.fastq/' _RA_GGACACTGAC.fastq
rename 's/_RA_GGTCCGTCTA.fastq/BW-Combo3-203_RA.fastq/' _RA_GGTCCGTCTA.fastq
rename 's/_RA_GGGCCACATA.fastq/BW-Combo3-204_RA.fastq/' _RA_GGGCCACATA.fastq
rename 's/_RA_GGCCGTGAGA.fastq/BW-Combo3-205_RA.fastq/' _RA_GGCCGTGAGA.fastq
rename 's/_RA_GGAGCAGGAA.fastq/BW-Combo3-206_RA.fastq/' _RA_GGAGCAGGAA.fastq
rename 's/_RA_GGAACCGAGA.fastq/BW-Combo3-207_RA.fastq/' _RA_GGAACCGAGA.fastq
rename 's/_RA_GGAAACATCG.fastq/BW-Combo3-208_RA.fastq/' _RA_GGAAACATCG.fastq
rename 's/_RA_GGAGTCAAGC.fastq/BW-Combo3-209_RA.fastq/' _RA_GGAGTCAAGC.fastq
rename 's/_RA_GGACAGATTC.fastq/BW-Combo3-210_RA.fastq/' _RA_GGACAGATTC.fastq
rename 's/_RA_GGTCTTCACA.fastq/BW-Combo3-211_RA.fastq/' _RA_GGTCTTCACA.fastq
rename 's/_RA_GGGCGAGTAA.fastq/BW-Combo3-212_RA.fastq/' _RA_GGGCGAGTAA.fastq
rename 's/_RA_GGCCTCCTGA.fastq/BW-Combo3-213_RA.fastq/' _RA_GGCCTCCTGA.fastq
rename 's/_RA_GGAGTCACTA.fastq/BW-Combo3-214_RA.fastq/' _RA_GGAGTCACTA.fastq
rename 's/_RA_GGAACGCTTA.fastq/BW-Combo3-215_RA.fastq/' _RA_GGAACGCTTA.fastq
rename 's/_RA_GGACATTGGC.fastq/BW-Combo3-216_RA.fastq/' _RA_GGACATTGGC.fastq
rename 's/_RA_GGCCTCTATC.fastq/BW-Combo3-217_RA.fastq/' _RA_GGCCTCTATC.fastq
rename 's/_RA_GGAGATGTAC.fastq/BW-Combo3-218_RA.fastq/' _RA_GGAGATGTAC.fastq
rename 's/_RA_GGTGAAGAGA.fastq/BW-Combo3-219_RA.fastq/' _RA_GGTGAAGAGA.fastq
rename 's/_RA_GGGCTAACGA.fastq/BW-Combo3-220_RA.fastq/' _RA_GGGCTAACGA.fastq
rename 's/_RA_GGCGAACTTA.fastq/BW-Combo3-221_RA.fastq/' _RA_GGCGAACTTA.fastq
rename 's/_RA_GGATCCTGTA.fastq/BW-Combo3-222_RA.fastq/' _RA_GGATCCTGTA.fastq
rename 's/_RA_GGAAGACGGA.fastq/BW-Combo3-223_RA.fastq/' _RA_GGAAGACGGA.fastq
rename 's/_RA_GGACCACTGT.fastq/BW-Combo3-224_RA.fastq/' _RA_GGACCACTGT.fastq
rename 's/_RA_GGCGACACAC.fastq/BW-Combo3-225_RA.fastq/' _RA_GGCGACACAC.fastq
rename 's/_RA_GGAGCACCTC.fastq/BW-Combo3-226_RA.fastq/' _RA_GGAGCACCTC.fastq
rename 's/_RA_GGTGGAACAA.fastq/BW-Combo3-227_RA.fastq/' _RA_GGTGGAACAA.fastq
rename 's/_RA_GGGCTCGGTA.fastq/BW-Combo3-228_RA.fastq/' _RA_GGGCTCGGTA.fastq
rename 's/_RA_GGCGACTGGA.fastq/BW-Combo3-229_RA.fastq/' _RA_GGCGACTGGA.fastq
rename 's/_RA_GGATTGAGGA.fastq/BW-Combo3-230_RA.fastq/' _RA_GGATTGAGGA.fastq
rename 's/_RA_GGAAGGTACA.fastq/BW-Combo3-231_RA.fastq/' _RA_GGAAGGTACA.fastq
rename 's/_RA_GGAACGTGAT.fastq/BW-Combo3-232_RA.fastq/' _RA_GGAACGTGAT.fastq
rename 's/_RA_GGCGGATTGC.fastq/BW-Combo3-233_RA.fastq/' _RA_GGCGGATTGC.fastq
rename 's/_RA_GGAGCCATGC.fastq/BW-Combo3-234_RA.fastq/' _RA_GGAGCCATGC.fastq
rename 's/_RA_GGTGGCTTCA.fastq/BW-Combo3-235_RA.fastq/' _RA_GGTGGCTTCA.fastq
rename 's/_RA_GGGGAGAACA.fastq/BW-Combo3-236_RA.fastq/' _RA_GGGGAGAACA.fastq
rename 's/_RA_GGCGCATACA.fastq/BW-Combo3-237_RA.fastq/' _RA_GGCGCATACA.fastq
rename 's/_RA_GGCAACCACA.fastq/BW-Combo3-238_RA.fastq/' _RA_GGCAACCACA.fastq
rename 's/_RA_GGACACAGAA.fastq/BW-Combo3-239_RA.fastq/' _RA_GGACACAGAA.fastq
rename 's/_RA_GGCGCTGATC.fastq/BW-Combo3-240_RA.fastq/' _RA_GGCGCTGATC.fastq
rename 's/_RA_GGCTAAGGTC.fastq/BW-Combo3-241_RA.fastq/' _RA_GGCTAAGGTC.fastq
rename 's/_RA_GGAGGCTAAC.fastq/BW-Combo3-242_RA.fastq/' _RA_GGAGGCTAAC.fastq
rename 's/_RA_GGTGGTGGTA.fastq/BW-Combo3-243_RA.fastq/' _RA_GGTGGTGGTA.fastq
rename 's/_RA_GGGGTGCGAA.fastq/BW-Combo3-244_RA.fastq/' _RA_GGGGTGCGAA.fastq
rename 's/_RA_GGCTCAATGA.fastq/BW-Combo3-245_RA.fastq/' _RA_GGCTCAATGA.fastq
rename 's/_RA_GGCAAGACTA.fastq/BW-Combo3-246_RA.fastq/' _RA_GGCAAGACTA.fastq
rename 's/_RA_GGACAGCAGA.fastq/BW-Combo3-247_RA.fastq/' _RA_GGACAGCAGA.fastq
rename 's/_RA_GGCAGATCTG.fastq/BW-Combo3-248_RA.fastq/' _RA_GGCAGATCTG.fastq
rename 's/_RA_GGGAACAGGC.fastq/BW-Combo3-249_RA.fastq/' _RA_GGGAACAGGC.fastq
rename 's/_RA_GGATAGCGAC.fastq/BW-Combo3-250_RA.fastq/' _RA_GGATAGCGAC.fastq
rename 's/_RA_GGTTCACGCA.fastq/BW-Combo3-251_RA.fastq/' _RA_GGTTCACGCA.fastq
rename 's/_RA_GGGTACGCAA.fastq/BW-Combo3-252_RA.fastq/' _RA_GGGTACGCAA.fastq
rename 's/_RA_GGCTGAGCCA.fastq/BW-Combo3-253_RA.fastq/' _RA_GGCTGAGCCA.fastq
rename 's/_RA_GGCAATGGAA.fastq/BW-Combo3-254_RA.fastq/' _RA_GGCAATGGAA.fastq
rename 's/_RA_GGACCTCCAA.fastq/BW-Combo3-255_RA.fastq/' _RA_GGACCTCCAA.fastq
rename 's/_RA_GGATGCCTAA.fastq/BW-Combo3-256_RA.fastq/' _RA_GGATGCCTAA.fastq
rename 's/_RA_GGGACAGTGC.fastq/BW-Combo3-257_RA.fastq/' _RA_GGGACAGTGC.fastq
rename 's/_RA_GGACGACAAG.fastq/BW-Combo3-258_RA.fastq/' _RA_GGACGACAAG.fastq
rename 's/_RA_GGACACGAGA.fastq/BW-Combo3-259_RA.fastq/' _RA_GGACACGAGA.fastq
rename 's/_RA_GGGTCGTAGA.fastq/BW-Combo3-260_RA.fastq/' _RA_GGGTCGTAGA.fastq
rename 's/_RA_GGCTGGCATA.fastq/BW-Combo3-261_RA.fastq/' _RA_GGCTGGCATA.fastq
rename 's/_RA_GGCACTTCGA.fastq/BW-Combo4-131_RA.fastq/' _RA_GGCACTTCGA.fastq
rename 's/_RA_GGACGCTCGA.fastq/BW-Combo4-132_RA.fastq/' _RA_GGACGCTCGA.fastq
rename 's/_RA_GGAACGAACG.fastq/BW-Combo4-133_RA.fastq/' _RA_GGAACGAACG.fastq
rename 's/_RA_GGGAGTTAGC.fastq/BW-Combo4-134_RA.fastq/' _RA_GGGAGTTAGC.fastq
rename 's/_RA_GGATTGGCTC.fastq/BW-Combo4-135_RA.fastq/' _RA_GGATTGGCTC.fastq
rename 's/_RA_GGAAGAGATC.fastq/BW-Combo4-136_RA.fastq/' _RA_GGAAGAGATC.fastq
rename 's/_RA_GGGTCTGTCA.fastq/BW-Combo4-137_RA.fastq/' _RA_GGGTCTGTCA.fastq
rename 's/_RA_GGGAATCTGA.fastq/BW-Combo4-138_RA.fastq/' _RA_GGGAATCTGA.fastq
rename 's/_RA_GGCAGCGTTA.fastq/BW-Combo4-139_RA.fastq/' _RA_GGCAGCGTTA.fastq
rename 's/_RA_GGACGTATCA.fastq/BW-Combo4-140_RA.fastq/' _RA_GGACGTATCA.fastq
rename 's/_RA_GGAGTACAAG.fastq/BW-Combo4-141_RA.fastq/' _RA_GGAGTACAAG.fastq
rename 's/_RA_GGGATGAATC.fastq/BW-Combo4-142_RA.fastq/' _RA_GGGATGAATC.fastq
rename 's/_RA_GGCAAGGAGC.fastq/BW-Combo4-143_RA.fastq/' _RA_GGCAAGGAGC.fastq
rename 's/_RA_GGAAGGACAC.fastq/BW-Combo4-144_RA.fastq/' _RA_GGAAGGACAC.fastq
rename 's/_RA_GGGTGTTCTA.fastq/BW-Combo4-145_RA.fastq/' _RA_GGGTGTTCTA.fastq
rename 's/_RA_GGGACTAGTA.fastq/BW-Combo4-146_RA.fastq/' _RA_GGGACTAGTA.fastq
rename 's/_RA_GGCATACCAA.fastq/BW-Combo5-028_RA.fastq/' _RA_GGCATACCAA.fastq
rename 's/_RA_GGACTATGCA.fastq/BW-Combo5-029_RA.fastq/' _RA_GGACTATGCA.fastq
rename 's/_RA_GGCATCAAGT.fastq/BW-Combo5-030_RA.fastq/' _RA_GGCATCAAGT.fastq
rename 's/_RA_GGGCCAAGAC.fastq/BW-Combo5-031_RA.fastq/' _RA_GGGCCAAGAC.fastq
rename 's/_RA_GGCACCTTAC.fastq/BW-Combo5-032_RA.fastq/' _RA_GGCACCTTAC.fastq
rename 's/_RA_GGAATCCGTC.fastq/BW-Combo5-033_RA.fastq/' _RA_GGAATCCGTC.fastq
rename 's/_RA_GGTAGGATGA.fastq/BW-Combo5-034_RA.fastq/' _RA_GGTAGGATGA.fastq
rename 's/_RA_GGGAGCTGAA.fastq/BW-Combo5-035_RA.fastq/' _RA_GGGAGCTGAA.fastq
rename 's/_RA_GGCCAGTTCA.fastq/BW-Combo5-036_RA.fastq/' _RA_GGCCAGTTCA.fastq
rename 's/_RA_GGAGAGTCAA.fastq/BW-Combo5-037_RA.fastq/' _RA_GGAGAGTCAA.fastq
rename 's/_RA_GGAGTGGTCA.fastq/BW-Combo5-038_RA.fastq/' _RA_GGAGTGGTCA.fastq
rename 's/_RB_GGCCATCCTC.fastq/BW-Combo3-193_RB.fastq/' _RB_GGCCATCCTC.fastq
rename 's/_RB_GGAATGTTGC.fastq/BW-Combo3-194_RB.fastq/' _RB_GGAATGTTGC.fastq
rename 's/_RB_GGTATCAGCA.fastq/BW-Combo3-195_RB.fastq/' _RB_GGTATCAGCA.fastq
rename 's/_RB_GGGATAGACA.fastq/BW-Combo3-196_RB.fastq/' _RB_GGGATAGACA.fastq
rename 's/_RB_GGCCGAAGTA.fastq/BW-Combo3-197_RB.fastq/' _RB_GGCCGAAGTA.fastq
rename 's/_RB_GGAGATCGCA.fastq/BW-Combo3-198_RB.fastq/' _RB_GGAGATCGCA.fastq
rename 's/_RB_GGAACAACCA.fastq/BW-Combo3-199_RB.fastq/' _RB_GGAACAACCA.fastq
rename 's/_RB_GGACAAGCTA.fastq/BW-Combo3-200_RB.fastq/' _RB_GGACAAGCTA.fastq
rename 's/_RB_GGCCGACAAC.fastq/BW-Combo3-201_RB.fastq/' _RB_GGCCGACAAC.fastq
rename 's/_RB_GGACACTGAC.fastq/BW-Combo3-202_RB.fastq/' _RB_GGACACTGAC.fastq
rename 's/_RB_GGTCCGTCTA.fastq/BW-Combo3-203_RB.fastq/' _RB_GGTCCGTCTA.fastq
rename 's/_RB_GGGCCACATA.fastq/BW-Combo3-204_RB.fastq/' _RB_GGGCCACATA.fastq
rename 's/_RB_GGCCGTGAGA.fastq/BW-Combo3-205_RB.fastq/' _RB_GGCCGTGAGA.fastq
rename 's/_RB_GGAGCAGGAA.fastq/BW-Combo3-206_RB.fastq/' _RB_GGAGCAGGAA.fastq
rename 's/_RB_GGAACCGAGA.fastq/BW-Combo3-207_RB.fastq/' _RB_GGAACCGAGA.fastq
rename 's/_RB_GGAAACATCG.fastq/BW-Combo3-208_RB.fastq/' _RB_GGAAACATCG.fastq
rename 's/_RB_GGAGTCAAGC.fastq/BW-Combo3-209_RB.fastq/' _RB_GGAGTCAAGC.fastq
rename 's/_RB_GGACAGATTC.fastq/BW-Combo3-210_RB.fastq/' _RB_GGACAGATTC.fastq
rename 's/_RB_GGTCTTCACA.fastq/BW-Combo3-211_RB.fastq/' _RB_GGTCTTCACA.fastq
rename 's/_RB_GGGCGAGTAA.fastq/BW-Combo3-212_RB.fastq/' _RB_GGGCGAGTAA.fastq
rename 's/_RB_GGCCTCCTGA.fastq/BW-Combo3-213_RB.fastq/' _RB_GGCCTCCTGA.fastq
rename 's/_RB_GGAGTCACTA.fastq/BW-Combo3-214_RB.fastq/' _RB_GGAGTCACTA.fastq
rename 's/_RB_GGAACGCTTA.fastq/BW-Combo3-215_RB.fastq/' _RB_GGAACGCTTA.fastq
rename 's/_RB_GGACATTGGC.fastq/BW-Combo3-216_RB.fastq/' _RB_GGACATTGGC.fastq
rename 's/_RB_GGCCTCTATC.fastq/BW-Combo3-217_RB.fastq/' _RB_GGCCTCTATC.fastq
rename 's/_RB_GGAGATGTAC.fastq/BW-Combo3-218_RB.fastq/' _RB_GGAGATGTAC.fastq
rename 's/_RB_GGTGAAGAGA.fastq/BW-Combo3-219_RB.fastq/' _RB_GGTGAAGAGA.fastq
rename 's/_RB_GGGCTAACGA.fastq/BW-Combo3-220_RB.fastq/' _RB_GGGCTAACGA.fastq
rename 's/_RB_GGCGAACTTA.fastq/BW-Combo3-221_RB.fastq/' _RB_GGCGAACTTA.fastq
rename 's/_RB_GGATCCTGTA.fastq/BW-Combo3-222_RB.fastq/' _RB_GGATCCTGTA.fastq
rename 's/_RB_GGAAGACGGA.fastq/BW-Combo3-223_RB.fastq/' _RB_GGAAGACGGA.fastq
rename 's/_RB_GGACCACTGT.fastq/BW-Combo3-224_RB.fastq/' _RB_GGACCACTGT.fastq
rename 's/_RB_GGCGACACAC.fastq/BW-Combo3-225_RB.fastq/' _RB_GGCGACACAC.fastq
rename 's/_RB_GGAGCACCTC.fastq/BW-Combo3-226_RB.fastq/' _RB_GGAGCACCTC.fastq
rename 's/_RB_GGTGGAACAA.fastq/BW-Combo3-227_RB.fastq/' _RB_GGTGGAACAA.fastq
rename 's/_RB_GGGCTCGGTA.fastq/BW-Combo3-228_RB.fastq/' _RB_GGGCTCGGTA.fastq
rename 's/_RB_GGCGACTGGA.fastq/BW-Combo3-229_RB.fastq/' _RB_GGCGACTGGA.fastq
rename 's/_RB_GGATTGAGGA.fastq/BW-Combo3-230_RB.fastq/' _RB_GGATTGAGGA.fastq
rename 's/_RB_GGAAGGTACA.fastq/BW-Combo3-231_RB.fastq/' _RB_GGAAGGTACA.fastq
rename 's/_RB_GGAACGTGAT.fastq/BW-Combo3-232_RB.fastq/' _RB_GGAACGTGAT.fastq
rename 's/_RB_GGCGGATTGC.fastq/BW-Combo3-233_RB.fastq/' _RB_GGCGGATTGC.fastq
rename 's/_RB_GGAGCCATGC.fastq/BW-Combo3-234_RB.fastq/' _RB_GGAGCCATGC.fastq
rename 's/_RB_GGTGGCTTCA.fastq/BW-Combo3-235_RB.fastq/' _RB_GGTGGCTTCA.fastq
rename 's/_RB_GGGGAGAACA.fastq/BW-Combo3-236_RB.fastq/' _RB_GGGGAGAACA.fastq
rename 's/_RB_GGCGCATACA.fastq/BW-Combo3-237_RB.fastq/' _RB_GGCGCATACA.fastq
rename 's/_RB_GGCAACCACA.fastq/BW-Combo3-238_RB.fastq/' _RB_GGCAACCACA.fastq
rename 's/_RB_GGACACAGAA.fastq/BW-Combo3-239_RB.fastq/' _RB_GGACACAGAA.fastq
rename 's/_RB_GGCGCTGATC.fastq/BW-Combo3-240_RB.fastq/' _RB_GGCGCTGATC.fastq
rename 's/_RB_GGCTAAGGTC.fastq/BW-Combo3-241_RB.fastq/' _RB_GGCTAAGGTC.fastq
rename 's/_RB_GGAGGCTAAC.fastq/BW-Combo3-242_RB.fastq/' _RB_GGAGGCTAAC.fastq
rename 's/_RB_GGTGGTGGTA.fastq/BW-Combo3-243_RB.fastq/' _RB_GGTGGTGGTA.fastq
rename 's/_RB_GGGGTGCGAA.fastq/BW-Combo3-244_RB.fastq/' _RB_GGGGTGCGAA.fastq
rename 's/_RB_GGCTCAATGA.fastq/BW-Combo3-245_RB.fastq/' _RB_GGCTCAATGA.fastq
rename 's/_RB_GGCAAGACTA.fastq/BW-Combo3-246_RB.fastq/' _RB_GGCAAGACTA.fastq
rename 's/_RB_GGACAGCAGA.fastq/BW-Combo3-247_RB.fastq/' _RB_GGACAGCAGA.fastq
rename 's/_RB_GGCAGATCTG.fastq/BW-Combo3-248_RB.fastq/' _RB_GGCAGATCTG.fastq
rename 's/_RB_GGGAACAGGC.fastq/BW-Combo3-249_RB.fastq/' _RB_GGGAACAGGC.fastq
rename 's/_RB_GGATAGCGAC.fastq/BW-Combo3-250_RB.fastq/' _RB_GGATAGCGAC.fastq
rename 's/_RB_GGTTCACGCA.fastq/BW-Combo3-251_RB.fastq/' _RB_GGTTCACGCA.fastq
rename 's/_RB_GGGTACGCAA.fastq/BW-Combo3-252_RB.fastq/' _RB_GGGTACGCAA.fastq
rename 's/_RB_GGCTGAGCCA.fastq/BW-Combo3-253_RB.fastq/' _RB_GGCTGAGCCA.fastq
rename 's/_RB_GGCAATGGAA.fastq/BW-Combo3-254_RB.fastq/' _RB_GGCAATGGAA.fastq
rename 's/_RB_GGACCTCCAA.fastq/BW-Combo3-255_RB.fastq/' _RB_GGACCTCCAA.fastq
rename 's/_RB_GGATGCCTAA.fastq/BW-Combo3-256_RB.fastq/' _RB_GGATGCCTAA.fastq
rename 's/_RB_GGGACAGTGC.fastq/BW-Combo3-257_RB.fastq/' _RB_GGGACAGTGC.fastq
rename 's/_RB_GGACGACAAG.fastq/BW-Combo3-258_RB.fastq/' _RB_GGACGACAAG.fastq
rename 's/_RB_GGACACGAGA.fastq/BW-Combo3-259_RB.fastq/' _RB_GGACACGAGA.fastq
rename 's/_RB_GGGTCGTAGA.fastq/BW-Combo3-260_RB.fastq/' _RB_GGGTCGTAGA.fastq
rename 's/_RB_GGCTGGCATA.fastq/BW-Combo3-261_RB.fastq/' _RB_GGCTGGCATA.fastq
rename 's/_RB_GGCACTTCGA.fastq/BW-Combo4-131_RB.fastq/' _RB_GGCACTTCGA.fastq
rename 's/_RB_GGACGCTCGA.fastq/BW-Combo4-132_RB.fastq/' _RB_GGACGCTCGA.fastq
rename 's/_RB_GGAACGAACG.fastq/BW-Combo4-133_RB.fastq/' _RB_GGAACGAACG.fastq
rename 's/_RB_GGGAGTTAGC.fastq/BW-Combo4-134_RB.fastq/' _RB_GGGAGTTAGC.fastq
rename 's/_RB_GGATTGGCTC.fastq/BW-Combo4-135_RB.fastq/' _RB_GGATTGGCTC.fastq
rename 's/_RB_GGAAGAGATC.fastq/BW-Combo4-136_RB.fastq/' _RB_GGAAGAGATC.fastq
rename 's/_RB_GGGTCTGTCA.fastq/BW-Combo4-137_RB.fastq/' _RB_GGGTCTGTCA.fastq
rename 's/_RB_GGGAATCTGA.fastq/BW-Combo4-138_RB.fastq/' _RB_GGGAATCTGA.fastq
rename 's/_RB_GGCAGCGTTA.fastq/BW-Combo4-139_RB.fastq/' _RB_GGCAGCGTTA.fastq
rename 's/_RB_GGACGTATCA.fastq/BW-Combo4-140_RB.fastq/' _RB_GGACGTATCA.fastq
rename 's/_RB_GGAGTACAAG.fastq/BW-Combo4-141_RB.fastq/' _RB_GGAGTACAAG.fastq
rename 's/_RB_GGGATGAATC.fastq/BW-Combo4-142_RB.fastq/' _RB_GGGATGAATC.fastq
rename 's/_RB_GGCAAGGAGC.fastq/BW-Combo4-143_RB.fastq/' _RB_GGCAAGGAGC.fastq
rename 's/_RB_GGAAGGACAC.fastq/BW-Combo4-144_RB.fastq/' _RB_GGAAGGACAC.fastq
rename 's/_RB_GGGTGTTCTA.fastq/BW-Combo4-145_RB.fastq/' _RB_GGGTGTTCTA.fastq
rename 's/_RB_GGGACTAGTA.fastq/BW-Combo4-146_RB.fastq/' _RB_GGGACTAGTA.fastq
rename 's/_RB_GGCATACCAA.fastq/BW-Combo5-028_RB.fastq/' _RB_GGCATACCAA.fastq
rename 's/_RB_GGACTATGCA.fastq/BW-Combo5-029_RB.fastq/' _RB_GGACTATGCA.fastq
rename 's/_RB_GGCATCAAGT.fastq/BW-Combo5-030_RB.fastq/' _RB_GGCATCAAGT.fastq
rename 's/_RB_GGGCCAAGAC.fastq/BW-Combo5-031_RB.fastq/' _RB_GGGCCAAGAC.fastq
rename 's/_RB_GGCACCTTAC.fastq/BW-Combo5-032_RB.fastq/' _RB_GGCACCTTAC.fastq
rename 's/_RB_GGAATCCGTC.fastq/BW-Combo5-033_RB.fastq/' _RB_GGAATCCGTC.fastq
rename 's/_RB_GGTAGGATGA.fastq/BW-Combo5-034_RB.fastq/' _RB_GGTAGGATGA.fastq
rename 's/_RB_GGGAGCTGAA.fastq/BW-Combo5-035_RB.fastq/' _RB_GGGAGCTGAA.fastq
rename 's/_RB_GGCCAGTTCA.fastq/BW-Combo5-036_RB.fastq/' _RB_GGCCAGTTCA.fastq
rename 's/_RB_GGAGAGTCAA.fastq/BW-Combo5-037_RB.fastq/' _RB_GGAGAGTCAA.fastq
rename 's/_RB_GGAGTGGTCA.fastq/BW-Combo5-038_RB.fastq/' _RB_GGAGTGGTCA.fastq
