rename 's/_RA_GGCCATCCTC.fastq/BW-Combo1-406_RA.fastq/' _RA_GGCCATCCTC.fastq
rename 's/_RA_GGAATGTTGC.fastq/BW-Combo1-407_RA.fastq/' _RA_GGAATGTTGC.fastq
rename 's/_RA_GGTATCAGCA.fastq/BW-Combo1-408_RA.fastq/' _RA_GGTATCAGCA.fastq
rename 's/_RA_GGGATAGACA.fastq/BW-Combo1-409_RA.fastq/' _RA_GGGATAGACA.fastq
rename 's/_RA_GGCCGAAGTA.fastq/BW-Combo1-410_RA.fastq/' _RA_GGCCGAAGTA.fastq
rename 's/_RA_GGAGATCGCA.fastq/BW-Combo3-407_RA.fastq/' _RA_GGAGATCGCA.fastq
rename 's/_RA_GGAACAACCA.fastq/BW-Combo3-408_RA.fastq/' _RA_GGAACAACCA.fastq
rename 's/_RA_GGACAAGCTA.fastq/BW-Combo3-409_RA.fastq/' _RA_GGACAAGCTA.fastq
rename 's/_RA_GGCCGACAAC.fastq/BW-Combo3-410_RA.fastq/' _RA_GGCCGACAAC.fastq
rename 's/_RA_GGACACTGAC.fastq/BW-Combo3-411_RA.fastq/' _RA_GGACACTGAC.fastq
rename 's/_RA_GGTCCGTCTA.fastq/BW-Combo3-412_RA.fastq/' _RA_GGTCCGTCTA.fastq
rename 's/_RA_GGGCCACATA.fastq/BW-Combo3-413_RA.fastq/' _RA_GGGCCACATA.fastq
rename 's/_RA_GGCCGTGAGA.fastq/BW-Combo3-414_RA.fastq/' _RA_GGCCGTGAGA.fastq
rename 's/_RA_GGAGCAGGAA.fastq/BW-Combo3-415_RA.fastq/' _RA_GGAGCAGGAA.fastq
rename 's/_RA_GGAACCGAGA.fastq/BW-Combo3-416_RA.fastq/' _RA_GGAACCGAGA.fastq
rename 's/_RA_GGAAACATCG.fastq/BW-Combo3-417_RA.fastq/' _RA_GGAAACATCG.fastq
rename 's/_RA_GGAGTCAAGC.fastq/BW-Combo3-418_RA.fastq/' _RA_GGAGTCAAGC.fastq
rename 's/_RA_GGACAGATTC.fastq/BW-Combo3-419_RA.fastq/' _RA_GGACAGATTC.fastq
rename 's/_RA_GGTCTTCACA.fastq/BW-Combo3-420_RA.fastq/' _RA_GGTCTTCACA.fastq
rename 's/_RA_GGGCGAGTAA.fastq/BW-Combo3-421_RA.fastq/' _RA_GGGCGAGTAA.fastq
rename 's/_RA_GGCCTCCTGA.fastq/BW-Combo3-422_RA.fastq/' _RA_GGCCTCCTGA.fastq
rename 's/_RA_GGAGTCACTA.fastq/BW-Combo3-423_RA.fastq/' _RA_GGAGTCACTA.fastq
rename 's/_RA_GGAACGCTTA.fastq/BW-Combo3-424_RA.fastq/' _RA_GGAACGCTTA.fastq
rename 's/_RA_GGACATTGGC.fastq/BW-Combo3-425_RA.fastq/' _RA_GGACATTGGC.fastq
rename 's/_RA_GGCCTCTATC.fastq/BW-Combo3-426_RA.fastq/' _RA_GGCCTCTATC.fastq
rename 's/_RA_GGAGATGTAC.fastq/BW-Combo3-427_RA.fastq/' _RA_GGAGATGTAC.fastq
rename 's/_RA_GGTGAAGAGA.fastq/BW-Combo3-428_RA.fastq/' _RA_GGTGAAGAGA.fastq
rename 's/_RA_GGGCTAACGA.fastq/BW-Combo3-429_RA.fastq/' _RA_GGGCTAACGA.fastq
rename 's/_RA_GGCGAACTTA.fastq/BW-Combo3-430_RA.fastq/' _RA_GGCGAACTTA.fastq
rename 's/_RA_GGATCCTGTA.fastq/BW-Combo3-431_RA.fastq/' _RA_GGATCCTGTA.fastq
rename 's/_RA_GGAAGACGGA.fastq/BW-Combo3-432_RA.fastq/' _RA_GGAAGACGGA.fastq
rename 's/_RA_GGACCACTGT.fastq/BW-Combo3-433_RA.fastq/' _RA_GGACCACTGT.fastq
rename 's/_RA_GGCGACACAC.fastq/BW-Combo3-434_RA.fastq/' _RA_GGCGACACAC.fastq
rename 's/_RA_GGAGCACCTC.fastq/BW-Combo3-435_RA.fastq/' _RA_GGAGCACCTC.fastq
rename 's/_RA_GGTGGAACAA.fastq/BW-Combo3-436_RA.fastq/' _RA_GGTGGAACAA.fastq
rename 's/_RA_GGGCTCGGTA.fastq/BW-Combo3-437_RA.fastq/' _RA_GGGCTCGGTA.fastq
rename 's/_RA_GGCGACTGGA.fastq/BW-Combo3-438_RA.fastq/' _RA_GGCGACTGGA.fastq
rename 's/_RA_GGATTGAGGA.fastq/BW-Combo3-439_RA.fastq/' _RA_GGATTGAGGA.fastq
rename 's/_RA_GGAAGGTACA.fastq/BW-Combo3-440_RA.fastq/' _RA_GGAAGGTACA.fastq
rename 's/_RA_GGAACGTGAT.fastq/BW-Combo3-441_RA.fastq/' _RA_GGAACGTGAT.fastq
rename 's/_RA_GGCGGATTGC.fastq/BW-Combo3-442_RA.fastq/' _RA_GGCGGATTGC.fastq
rename 's/_RA_GGAGCCATGC.fastq/BW-Combo3-443_RA.fastq/' _RA_GGAGCCATGC.fastq
rename 's/_RA_GGTGGCTTCA.fastq/BW-Combo3-444_RA.fastq/' _RA_GGTGGCTTCA.fastq
rename 's/_RA_GGGGAGAACA.fastq/BW-Combo3-445_RA.fastq/' _RA_GGGGAGAACA.fastq
rename 's/_RA_GGCGCATACA.fastq/BW-Combo3-446_RA.fastq/' _RA_GGCGCATACA.fastq
rename 's/_RA_GGCAACCACA.fastq/BW-Combo3-447_RA.fastq/' _RA_GGCAACCACA.fastq
rename 's/_RA_GGACACAGAA.fastq/BestRAD_B06_RA.fastq/' _RA_GGACACAGAA.fastq
rename 's/_RA_GGCGCTGATC.fastq/BestRAD_A06_RA.fastq/' _RA_GGCGCTGATC.fastq
rename 's/_RA_GGCTAAGGTC.fastq/BestRAD_H07_RA.fastq/' _RA_GGCTAAGGTC.fastq
rename 's/_RA_GGAGGCTAAC.fastq/BestRAD_G07_RA.fastq/' _RA_GGAGGCTAAC.fastq
rename 's/_RA_GGTGGTGGTA.fastq/BestRAD_F07_RA.fastq/' _RA_GGTGGTGGTA.fastq
rename 's/_RA_GGGGTGCGAA.fastq/BestRAD_E07_RA.fastq/' _RA_GGGGTGCGAA.fastq
rename 's/_RA_GGCTCAATGA.fastq/BestRAD_D07_RA.fastq/' _RA_GGCTCAATGA.fastq
rename 's/_RA_GGCAAGACTA.fastq/BestRAD_C07_RA.fastq/' _RA_GGCAAGACTA.fastq
rename 's/_RA_GGACAGCAGA.fastq/BestRAD_B07_RA.fastq/' _RA_GGACAGCAGA.fastq
rename 's/_RA_GGCAGATCTG.fastq/BestRAD_A07_RA.fastq/' _RA_GGCAGATCTG.fastq
rename 's/_RA_GGGAACAGGC.fastq/BestRAD_H08_RA.fastq/' _RA_GGGAACAGGC.fastq
rename 's/_RA_GGATAGCGAC.fastq/BestRAD_G08_RA.fastq/' _RA_GGATAGCGAC.fastq
rename 's/_RA_GGTTCACGCA.fastq/BestRAD_F08_RA.fastq/' _RA_GGTTCACGCA.fastq
rename 's/_RA_GGGTACGCAA.fastq/BestRAD_E08_RA.fastq/' _RA_GGGTACGCAA.fastq
rename 's/_RA_GGCTGAGCCA.fastq/BestRAD_D08_RA.fastq/' _RA_GGCTGAGCCA.fastq
rename 's/_RA_GGCAATGGAA.fastq/BestRAD_C08_RA.fastq/' _RA_GGCAATGGAA.fastq
rename 's/_RA_GGACCTCCAA.fastq/BestRAD_B08_RA.fastq/' _RA_GGACCTCCAA.fastq
rename 's/_RA_GGATGCCTAA.fastq/BestRAD_A08_RA.fastq/' _RA_GGATGCCTAA.fastq
rename 's/_RA_GGGACAGTGC.fastq/BestRAD_H09_RA.fastq/' _RA_GGGACAGTGC.fastq
rename 's/_RA_GGACGACAAG.fastq/BestRAD_G09_RA.fastq/' _RA_GGACGACAAG.fastq
rename 's/_RA_GGACACGAGA.fastq/BestRAD_F09_RA.fastq/' _RA_GGACACGAGA.fastq
rename 's/_RA_GGGTCGTAGA.fastq/BestRAD_E09_RA.fastq/' _RA_GGGTCGTAGA.fastq
rename 's/_RA_GGCTGGCATA.fastq/BestRAD_D09_RA.fastq/' _RA_GGCTGGCATA.fastq
rename 's/_RA_GGCACTTCGA.fastq/BestRAD_C09_RA.fastq/' _RA_GGCACTTCGA.fastq
rename 's/_RA_GGACGCTCGA.fastq/BestRAD_B09_RA.fastq/' _RA_GGACGCTCGA.fastq
rename 's/_RA_GGAACGAACG.fastq/BestRAD_A09_RA.fastq/' _RA_GGAACGAACG.fastq
rename 's/_RA_GGGAGTTAGC.fastq/BestRAD_H10_RA.fastq/' _RA_GGGAGTTAGC.fastq
rename 's/_RA_GGATTGGCTC.fastq/BestRAD_G10_RA.fastq/' _RA_GGATTGGCTC.fastq
rename 's/_RA_GGAAGAGATC.fastq/BestRAD_F10_RA.fastq/' _RA_GGAAGAGATC.fastq
rename 's/_RA_GGGTCTGTCA.fastq/BestRAD_E10_RA.fastq/' _RA_GGGTCTGTCA.fastq
rename 's/_RA_GGGAATCTGA.fastq/BestRAD_D10_RA.fastq/' _RA_GGGAATCTGA.fastq
rename 's/_RA_GGCAGCGTTA.fastq/BestRAD_C10_RA.fastq/' _RA_GGCAGCGTTA.fastq
rename 's/_RA_GGACGTATCA.fastq/BestRAD_B10_RA.fastq/' _RA_GGACGTATCA.fastq
rename 's/_RA_GGAGTACAAG.fastq/BestRAD_A10_RA.fastq/' _RA_GGAGTACAAG.fastq
rename 's/_RA_GGGATGAATC.fastq/BestRAD_H11_RA.fastq/' _RA_GGGATGAATC.fastq
rename 's/_RA_GGCAAGGAGC.fastq/BestRAD_G11_RA.fastq/' _RA_GGCAAGGAGC.fastq
rename 's/_RA_GGAAGGACAC.fastq/BestRAD_F11_RA.fastq/' _RA_GGAAGGACAC.fastq
rename 's/_RA_GGGTGTTCTA.fastq/BestRAD_E11_RA.fastq/' _RA_GGGTGTTCTA.fastq
rename 's/_RA_GGGACTAGTA.fastq/BestRAD_D11_RA.fastq/' _RA_GGGACTAGTA.fastq
rename 's/_RA_GGCATACCAA.fastq/BestRAD_C11_RA.fastq/' _RA_GGCATACCAA.fastq
rename 's/_RA_GGACTATGCA.fastq/BestRAD_B11_RA.fastq/' _RA_GGACTATGCA.fastq
rename 's/_RA_GGCATCAAGT.fastq/BestRAD_A11_RA.fastq/' _RA_GGCATCAAGT.fastq
rename 's/_RA_GGGCCAAGAC.fastq/BestRAD_H12_RA.fastq/' _RA_GGGCCAAGAC.fastq
rename 's/_RA_GGCACCTTAC.fastq/BestRAD_G12_RA.fastq/' _RA_GGCACCTTAC.fastq
rename 's/_RA_GGAATCCGTC.fastq/BestRAD_F12_RA.fastq/' _RA_GGAATCCGTC.fastq
rename 's/_RA_GGTAGGATGA.fastq/BestRAD_E12_RA.fastq/' _RA_GGTAGGATGA.fastq
rename 's/_RA_GGGAGCTGAA.fastq/BestRAD_D12_RA.fastq/' _RA_GGGAGCTGAA.fastq
rename 's/_RA_GGCCAGTTCA.fastq/BestRAD_C12_RA.fastq/' _RA_GGCCAGTTCA.fastq
rename 's/_RA_GGAGAGTCAA.fastq/BestRAD_B12_RA.fastq/' _RA_GGAGAGTCAA.fastq
rename 's/_RA_GGAGTGGTCA.fastq/BestRAD_A12_RA.fastq/' _RA_GGAGTGGTCA.fastq
rename 's/_RB_GGCCATCCTC.fastq/BW-Combo1-406_RB.fastq/' _RB_GGCCATCCTC.fastq
rename 's/_RB_GGAATGTTGC.fastq/BW-Combo1-407_RB.fastq/' _RB_GGAATGTTGC.fastq
rename 's/_RB_GGTATCAGCA.fastq/BW-Combo1-408_RB.fastq/' _RB_GGTATCAGCA.fastq
rename 's/_RB_GGGATAGACA.fastq/BW-Combo1-409_RB.fastq/' _RB_GGGATAGACA.fastq
rename 's/_RB_GGCCGAAGTA.fastq/BW-Combo1-410_RB.fastq/' _RB_GGCCGAAGTA.fastq
rename 's/_RB_GGAGATCGCA.fastq/BW-Combo3-407_RB.fastq/' _RB_GGAGATCGCA.fastq
rename 's/_RB_GGAACAACCA.fastq/BW-Combo3-408_RB.fastq/' _RB_GGAACAACCA.fastq
rename 's/_RB_GGACAAGCTA.fastq/BW-Combo3-409_RB.fastq/' _RB_GGACAAGCTA.fastq
rename 's/_RB_GGCCGACAAC.fastq/BW-Combo3-410_RB.fastq/' _RB_GGCCGACAAC.fastq
rename 's/_RB_GGACACTGAC.fastq/BW-Combo3-411_RB.fastq/' _RB_GGACACTGAC.fastq
rename 's/_RB_GGTCCGTCTA.fastq/BW-Combo3-412_RB.fastq/' _RB_GGTCCGTCTA.fastq
rename 's/_RB_GGGCCACATA.fastq/BW-Combo3-413_RB.fastq/' _RB_GGGCCACATA.fastq
rename 's/_RB_GGCCGTGAGA.fastq/BW-Combo3-414_RB.fastq/' _RB_GGCCGTGAGA.fastq
rename 's/_RB_GGAGCAGGAA.fastq/BW-Combo3-415_RB.fastq/' _RB_GGAGCAGGAA.fastq
rename 's/_RB_GGAACCGAGA.fastq/BW-Combo3-416_RB.fastq/' _RB_GGAACCGAGA.fastq
rename 's/_RB_GGAAACATCG.fastq/BW-Combo3-417_RB.fastq/' _RB_GGAAACATCG.fastq
rename 's/_RB_GGAGTCAAGC.fastq/BW-Combo3-418_RB.fastq/' _RB_GGAGTCAAGC.fastq
rename 's/_RB_GGACAGATTC.fastq/BW-Combo3-419_RB.fastq/' _RB_GGACAGATTC.fastq
rename 's/_RB_GGTCTTCACA.fastq/BW-Combo3-420_RB.fastq/' _RB_GGTCTTCACA.fastq
rename 's/_RB_GGGCGAGTAA.fastq/BW-Combo3-421_RB.fastq/' _RB_GGGCGAGTAA.fastq
rename 's/_RB_GGCCTCCTGA.fastq/BW-Combo3-422_RB.fastq/' _RB_GGCCTCCTGA.fastq
rename 's/_RB_GGAGTCACTA.fastq/BW-Combo3-423_RB.fastq/' _RB_GGAGTCACTA.fastq
rename 's/_RB_GGAACGCTTA.fastq/BW-Combo3-424_RB.fastq/' _RB_GGAACGCTTA.fastq
rename 's/_RB_GGACATTGGC.fastq/BW-Combo3-425_RB.fastq/' _RB_GGACATTGGC.fastq
rename 's/_RB_GGCCTCTATC.fastq/BW-Combo3-426_RB.fastq/' _RB_GGCCTCTATC.fastq
rename 's/_RB_GGAGATGTAC.fastq/BW-Combo3-427_RB.fastq/' _RB_GGAGATGTAC.fastq
rename 's/_RB_GGTGAAGAGA.fastq/BW-Combo3-428_RB.fastq/' _RB_GGTGAAGAGA.fastq
rename 's/_RB_GGGCTAACGA.fastq/BW-Combo3-429_RB.fastq/' _RB_GGGCTAACGA.fastq
rename 's/_RB_GGCGAACTTA.fastq/BW-Combo3-430_RB.fastq/' _RB_GGCGAACTTA.fastq
rename 's/_RB_GGATCCTGTA.fastq/BW-Combo3-431_RB.fastq/' _RB_GGATCCTGTA.fastq
rename 's/_RB_GGAAGACGGA.fastq/BW-Combo3-432_RB.fastq/' _RB_GGAAGACGGA.fastq
rename 's/_RB_GGACCACTGT.fastq/BW-Combo3-433_RB.fastq/' _RB_GGACCACTGT.fastq
rename 's/_RB_GGCGACACAC.fastq/BW-Combo3-434_RB.fastq/' _RB_GGCGACACAC.fastq
rename 's/_RB_GGAGCACCTC.fastq/BW-Combo3-435_RB.fastq/' _RB_GGAGCACCTC.fastq
rename 's/_RB_GGTGGAACAA.fastq/BW-Combo3-436_RB.fastq/' _RB_GGTGGAACAA.fastq
rename 's/_RB_GGGCTCGGTA.fastq/BW-Combo3-437_RB.fastq/' _RB_GGGCTCGGTA.fastq
rename 's/_RB_GGCGACTGGA.fastq/BW-Combo3-438_RB.fastq/' _RB_GGCGACTGGA.fastq
rename 's/_RB_GGATTGAGGA.fastq/BW-Combo3-439_RB.fastq/' _RB_GGATTGAGGA.fastq
rename 's/_RB_GGAAGGTACA.fastq/BW-Combo3-440_RB.fastq/' _RB_GGAAGGTACA.fastq
rename 's/_RB_GGAACGTGAT.fastq/BW-Combo3-441_RB.fastq/' _RB_GGAACGTGAT.fastq
rename 's/_RB_GGCGGATTGC.fastq/BW-Combo3-442_RB.fastq/' _RB_GGCGGATTGC.fastq
rename 's/_RB_GGAGCCATGC.fastq/BW-Combo3-443_RB.fastq/' _RB_GGAGCCATGC.fastq
rename 's/_RB_GGTGGCTTCA.fastq/BW-Combo3-444_RB.fastq/' _RB_GGTGGCTTCA.fastq
rename 's/_RB_GGGGAGAACA.fastq/BW-Combo3-445_RB.fastq/' _RB_GGGGAGAACA.fastq
rename 's/_RB_GGCGCATACA.fastq/BW-Combo3-446_RB.fastq/' _RB_GGCGCATACA.fastq
rename 's/_RB_GGCAACCACA.fastq/BW-Combo3-447_RB.fastq/' _RB_GGCAACCACA.fastq
rename 's/_RB_GGACACAGAA.fastq/BestRAD_B06_RB.fastq/' _RB_GGACACAGAA.fastq
rename 's/_RB_GGCGCTGATC.fastq/BestRAD_A06_RB.fastq/' _RB_GGCGCTGATC.fastq
rename 's/_RB_GGCTAAGGTC.fastq/BestRAD_H07_RB.fastq/' _RB_GGCTAAGGTC.fastq
rename 's/_RB_GGAGGCTAAC.fastq/BestRAD_G07_RB.fastq/' _RB_GGAGGCTAAC.fastq
rename 's/_RB_GGTGGTGGTA.fastq/BestRAD_F07_RB.fastq/' _RB_GGTGGTGGTA.fastq
rename 's/_RB_GGGGTGCGAA.fastq/BestRAD_E07_RB.fastq/' _RB_GGGGTGCGAA.fastq
rename 's/_RB_GGCTCAATGA.fastq/BestRAD_D07_RB.fastq/' _RB_GGCTCAATGA.fastq
rename 's/_RB_GGCAAGACTA.fastq/BestRAD_C07_RB.fastq/' _RB_GGCAAGACTA.fastq
rename 's/_RB_GGACAGCAGA.fastq/BestRAD_B07_RB.fastq/' _RB_GGACAGCAGA.fastq
rename 's/_RB_GGCAGATCTG.fastq/BestRAD_A07_RB.fastq/' _RB_GGCAGATCTG.fastq
rename 's/_RB_GGGAACAGGC.fastq/BestRAD_H08_RB.fastq/' _RB_GGGAACAGGC.fastq
rename 's/_RB_GGATAGCGAC.fastq/BestRAD_G08_RB.fastq/' _RB_GGATAGCGAC.fastq
rename 's/_RB_GGTTCACGCA.fastq/BestRAD_F08_RB.fastq/' _RB_GGTTCACGCA.fastq
rename 's/_RB_GGGTACGCAA.fastq/BestRAD_E08_RB.fastq/' _RB_GGGTACGCAA.fastq
rename 's/_RB_GGCTGAGCCA.fastq/BestRAD_D08_RB.fastq/' _RB_GGCTGAGCCA.fastq
rename 's/_RB_GGCAATGGAA.fastq/BestRAD_C08_RB.fastq/' _RB_GGCAATGGAA.fastq
rename 's/_RB_GGACCTCCAA.fastq/BestRAD_B08_RB.fastq/' _RB_GGACCTCCAA.fastq
rename 's/_RB_GGATGCCTAA.fastq/BestRAD_A08_RB.fastq/' _RB_GGATGCCTAA.fastq
rename 's/_RB_GGGACAGTGC.fastq/BestRAD_H09_RB.fastq/' _RB_GGGACAGTGC.fastq
rename 's/_RB_GGACGACAAG.fastq/BestRAD_G09_RB.fastq/' _RB_GGACGACAAG.fastq
rename 's/_RB_GGACACGAGA.fastq/BestRAD_F09_RB.fastq/' _RB_GGACACGAGA.fastq
rename 's/_RB_GGGTCGTAGA.fastq/BestRAD_E09_RB.fastq/' _RB_GGGTCGTAGA.fastq
rename 's/_RB_GGCTGGCATA.fastq/BestRAD_D09_RB.fastq/' _RB_GGCTGGCATA.fastq
rename 's/_RB_GGCACTTCGA.fastq/BestRAD_C09_RB.fastq/' _RB_GGCACTTCGA.fastq
rename 's/_RB_GGACGCTCGA.fastq/BestRAD_B09_RB.fastq/' _RB_GGACGCTCGA.fastq
rename 's/_RB_GGAACGAACG.fastq/BestRAD_A09_RB.fastq/' _RB_GGAACGAACG.fastq
rename 's/_RB_GGGAGTTAGC.fastq/BestRAD_H10_RB.fastq/' _RB_GGGAGTTAGC.fastq
rename 's/_RB_GGATTGGCTC.fastq/BestRAD_G10_RB.fastq/' _RB_GGATTGGCTC.fastq
rename 's/_RB_GGAAGAGATC.fastq/BestRAD_F10_RB.fastq/' _RB_GGAAGAGATC.fastq
rename 's/_RB_GGGTCTGTCA.fastq/BestRAD_E10_RB.fastq/' _RB_GGGTCTGTCA.fastq
rename 's/_RB_GGGAATCTGA.fastq/BestRAD_D10_RB.fastq/' _RB_GGGAATCTGA.fastq
rename 's/_RB_GGCAGCGTTA.fastq/BestRAD_C10_RB.fastq/' _RB_GGCAGCGTTA.fastq
rename 's/_RB_GGACGTATCA.fastq/BestRAD_B10_RB.fastq/' _RB_GGACGTATCA.fastq
rename 's/_RB_GGAGTACAAG.fastq/BestRAD_A10_RB.fastq/' _RB_GGAGTACAAG.fastq
rename 's/_RB_GGGATGAATC.fastq/BestRAD_H11_RB.fastq/' _RB_GGGATGAATC.fastq
rename 's/_RB_GGCAAGGAGC.fastq/BestRAD_G11_RB.fastq/' _RB_GGCAAGGAGC.fastq
rename 's/_RB_GGAAGGACAC.fastq/BestRAD_F11_RB.fastq/' _RB_GGAAGGACAC.fastq
rename 's/_RB_GGGTGTTCTA.fastq/BestRAD_E11_RB.fastq/' _RB_GGGTGTTCTA.fastq
rename 's/_RB_GGGACTAGTA.fastq/BestRAD_D11_RB.fastq/' _RB_GGGACTAGTA.fastq
rename 's/_RB_GGCATACCAA.fastq/BestRAD_C11_RB.fastq/' _RB_GGCATACCAA.fastq
rename 's/_RB_GGACTATGCA.fastq/BestRAD_B11_RB.fastq/' _RB_GGACTATGCA.fastq
rename 's/_RB_GGCATCAAGT.fastq/BestRAD_A11_RB.fastq/' _RB_GGCATCAAGT.fastq
rename 's/_RB_GGGCCAAGAC.fastq/BestRAD_H12_RB.fastq/' _RB_GGGCCAAGAC.fastq
rename 's/_RB_GGCACCTTAC.fastq/BestRAD_G12_RB.fastq/' _RB_GGCACCTTAC.fastq
rename 's/_RB_GGAATCCGTC.fastq/BestRAD_F12_RB.fastq/' _RB_GGAATCCGTC.fastq
rename 's/_RB_GGTAGGATGA.fastq/BestRAD_E12_RB.fastq/' _RB_GGTAGGATGA.fastq
rename 's/_RB_GGGAGCTGAA.fastq/BestRAD_D12_RB.fastq/' _RB_GGGAGCTGAA.fastq
rename 's/_RB_GGCCAGTTCA.fastq/BestRAD_C12_RB.fastq/' _RB_GGCCAGTTCA.fastq
rename 's/_RB_GGAGAGTCAA.fastq/BestRAD_B12_RB.fastq/' _RB_GGAGAGTCAA.fastq
rename 's/_RB_GGAGTGGTCA.fastq/BestRAD_A12_RB.fastq/' _RB_GGAGTGGTCA.fastq
