rename 's/_RA_GGCCATCCTC.fastq/BW-Combo1-406_RA.fastq/' _RA_GGCCATCCTC.fastq
rename 's/_RA_GGAATGTTGC.fastq/BW-Combo1-407_RA.fastq/' _RA_GGAATGTTGC.fastq
rename 's/_RA_GGTATCAGCA.fastq/BW-Combo1-408_RA.fastq/' _RA_GGTATCAGCA.fastq
rename 's/_RA_GGGATAGACA.fastq/BW-Combo1-409_RA.fastq/' _RA_GGGATAGACA.fastq
rename 's/_RA_GGCCGAAGTA.fastq/BW-Combo1-410_RA.fastq/' _RA_GGCCGAAGTA.fastq
rename 's/_RA_GGAGATCGCA.fastq/BW-Combo3-407_RA.fastq/' _RA_GGAGATCGCA.fastq
rename 's/_RA_GGAACAACCA.fastq/BW-Combo3-408_RA.fastq/' _RA_GGAACAACCA.fastq
rename 's/_RA_GGACAAGCTA.fastq/BW-Combo3-409_RA.fastq/' _RA_GGACAAGCTA.fastq
rename 's/_RA_GGCCGACAAC.fastq/BW-Combo3-410_RA.fastq/' _RA_GGCCGACAAC.fastq
rename 's/_RA_GGACACTGAC.fastq/BW-Combo3-411_RA.fastq/' _RA_GGACACTGAC.fastq
rename 's/_RA_GGTCCGTCTA.fastq/BW-Combo3-412_RA.fastq/' _RA_GGTCCGTCTA.fastq
rename 's/_RA_GGGCCACATA.fastq/BW-Combo3-413_RA.fastq/' _RA_GGGCCACATA.fastq
rename 's/_RA_GGCCGTGAGA.fastq/BW-Combo3-414_RA.fastq/' _RA_GGCCGTGAGA.fastq
rename 's/_RA_GGAGCAGGAA.fastq/BW-Combo3-415_RA.fastq/' _RA_GGAGCAGGAA.fastq
rename 's/_RA_GGAACCGAGA.fastq/BW-Combo3-416_RA.fastq/' _RA_GGAACCGAGA.fastq
rename 's/_RA_GGAAACATCG.fastq/BW-Combo3-417_RA.fastq/' _RA_GGAAACATCG.fastq
rename 's/_RA_GGAGTCAAGC.fastq/BW-Combo3-418_RA.fastq/' _RA_GGAGTCAAGC.fastq
rename 's/_RA_GGACAGATTC.fastq/BW-Combo3-419_RA.fastq/' _RA_GGACAGATTC.fastq
rename 's/_RA_GGTCTTCACA.fastq/BW-Combo3-420_RA.fastq/' _RA_GGTCTTCACA.fastq
rename 's/_RA_GGGCGAGTAA.fastq/BW-Combo3-421_RA.fastq/' _RA_GGGCGAGTAA.fastq
rename 's/_RA_GGCCTCCTGA.fastq/BW-Combo3-422_RA.fastq/' _RA_GGCCTCCTGA.fastq
rename 's/_RA_GGAGTCACTA.fastq/BW-Combo3-423_RA.fastq/' _RA_GGAGTCACTA.fastq
rename 's/_RA_GGAACGCTTA.fastq/BW-Combo3-424_RA.fastq/' _RA_GGAACGCTTA.fastq
rename 's/_RA_GGACATTGGC.fastq/BW-Combo3-425_RA.fastq/' _RA_GGACATTGGC.fastq
rename 's/_RA_GGCCTCTATC.fastq/BW-Combo3-426_RA.fastq/' _RA_GGCCTCTATC.fastq
rename 's/_RA_GGAGATGTAC.fastq/BW-Combo3-427_RA.fastq/' _RA_GGAGATGTAC.fastq
rename 's/_RA_GGTGAAGAGA.fastq/BW-Combo3-428_RA.fastq/' _RA_GGTGAAGAGA.fastq
rename 's/_RA_GGGCTAACGA.fastq/BW-Combo3-429_RA.fastq/' _RA_GGGCTAACGA.fastq
rename 's/_RA_GGCGAACTTA.fastq/BW-Combo3-430_RA.fastq/' _RA_GGCGAACTTA.fastq
rename 's/_RA_GGATCCTGTA.fastq/BW-Combo3-431_RA.fastq/' _RA_GGATCCTGTA.fastq
rename 's/_RA_GGAAGACGGA.fastq/BW-Combo3-432_RA.fastq/' _RA_GGAAGACGGA.fastq
rename 's/_RA_GGACCACTGT.fastq/BW-Combo3-433_RA.fastq/' _RA_GGACCACTGT.fastq
rename 's/_RA_GGCGACACAC.fastq/BW-Combo3-434_RA.fastq/' _RA_GGCGACACAC.fastq
rename 's/_RA_GGAGCACCTC.fastq/BW-Combo3-435_RA.fastq/' _RA_GGAGCACCTC.fastq
rename 's/_RA_GGTGGAACAA.fastq/BW-Combo3-436_RA.fastq/' _RA_GGTGGAACAA.fastq
rename 's/_RA_GGGCTCGGTA.fastq/BW-Combo3-437_RA.fastq/' _RA_GGGCTCGGTA.fastq
rename 's/_RA_GGCGACTGGA.fastq/BW-Combo3-438_RA.fastq/' _RA_GGCGACTGGA.fastq
rename 's/_RA_GGATTGAGGA.fastq/BW-Combo3-439_RA.fastq/' _RA_GGATTGAGGA.fastq
rename 's/_RA_GGAAGGTACA.fastq/BW-Combo3-440_RA.fastq/' _RA_GGAAGGTACA.fastq
rename 's/_RA_GGAACGTGAT.fastq/BW-Combo3-441_RA.fastq/' _RA_GGAACGTGAT.fastq
rename 's/_RA_GGCGGATTGC.fastq/BW-Combo3-442_RA.fastq/' _RA_GGCGGATTGC.fastq
rename 's/_RA_GGAGCCATGC.fastq/BW-Combo3-443_RA.fastq/' _RA_GGAGCCATGC.fastq
rename 's/_RA_GGTGGCTTCA.fastq/BW-Combo3-444_RA.fastq/' _RA_GGTGGCTTCA.fastq
rename 's/_RA_GGGGAGAACA.fastq/BW-Combo3-445_RA.fastq/' _RA_GGGGAGAACA.fastq
rename 's/_RA_GGCGCATACA.fastq/BW-Combo3-446_RA.fastq/' _RA_GGCGCATACA.fastq
rename 's/_RA_GGCAACCACA.fastq/BW-Combo3-447_RA.fastq/' _RA_GGCAACCACA.fastq
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RA_NA/NA_RA.fastq/' _RA_NA
rename 's/_RB_GGCCATCCTC.fastq/BW-Combo1-406_RB.fastq/' _RB_GGCCATCCTC.fastq
rename 's/_RB_GGAATGTTGC.fastq/BW-Combo1-407_RB.fastq/' _RB_GGAATGTTGC.fastq
rename 's/_RB_GGTATCAGCA.fastq/BW-Combo1-408_RB.fastq/' _RB_GGTATCAGCA.fastq
rename 's/_RB_GGGATAGACA.fastq/BW-Combo1-409_RB.fastq/' _RB_GGGATAGACA.fastq
rename 's/_RB_GGCCGAAGTA.fastq/BW-Combo1-410_RB.fastq/' _RB_GGCCGAAGTA.fastq
rename 's/_RB_GGAGATCGCA.fastq/BW-Combo3-407_RB.fastq/' _RB_GGAGATCGCA.fastq
rename 's/_RB_GGAACAACCA.fastq/BW-Combo3-408_RB.fastq/' _RB_GGAACAACCA.fastq
rename 's/_RB_GGACAAGCTA.fastq/BW-Combo3-409_RB.fastq/' _RB_GGACAAGCTA.fastq
rename 's/_RB_GGCCGACAAC.fastq/BW-Combo3-410_RB.fastq/' _RB_GGCCGACAAC.fastq
rename 's/_RB_GGACACTGAC.fastq/BW-Combo3-411_RB.fastq/' _RB_GGACACTGAC.fastq
rename 's/_RB_GGTCCGTCTA.fastq/BW-Combo3-412_RB.fastq/' _RB_GGTCCGTCTA.fastq
rename 's/_RB_GGGCCACATA.fastq/BW-Combo3-413_RB.fastq/' _RB_GGGCCACATA.fastq
rename 's/_RB_GGCCGTGAGA.fastq/BW-Combo3-414_RB.fastq/' _RB_GGCCGTGAGA.fastq
rename 's/_RB_GGAGCAGGAA.fastq/BW-Combo3-415_RB.fastq/' _RB_GGAGCAGGAA.fastq
rename 's/_RB_GGAACCGAGA.fastq/BW-Combo3-416_RB.fastq/' _RB_GGAACCGAGA.fastq
rename 's/_RB_GGAAACATCG.fastq/BW-Combo3-417_RB.fastq/' _RB_GGAAACATCG.fastq
rename 's/_RB_GGAGTCAAGC.fastq/BW-Combo3-418_RB.fastq/' _RB_GGAGTCAAGC.fastq
rename 's/_RB_GGACAGATTC.fastq/BW-Combo3-419_RB.fastq/' _RB_GGACAGATTC.fastq
rename 's/_RB_GGTCTTCACA.fastq/BW-Combo3-420_RB.fastq/' _RB_GGTCTTCACA.fastq
rename 's/_RB_GGGCGAGTAA.fastq/BW-Combo3-421_RB.fastq/' _RB_GGGCGAGTAA.fastq
rename 's/_RB_GGCCTCCTGA.fastq/BW-Combo3-422_RB.fastq/' _RB_GGCCTCCTGA.fastq
rename 's/_RB_GGAGTCACTA.fastq/BW-Combo3-423_RB.fastq/' _RB_GGAGTCACTA.fastq
rename 's/_RB_GGAACGCTTA.fastq/BW-Combo3-424_RB.fastq/' _RB_GGAACGCTTA.fastq
rename 's/_RB_GGACATTGGC.fastq/BW-Combo3-425_RB.fastq/' _RB_GGACATTGGC.fastq
rename 's/_RB_GGCCTCTATC.fastq/BW-Combo3-426_RB.fastq/' _RB_GGCCTCTATC.fastq
rename 's/_RB_GGAGATGTAC.fastq/BW-Combo3-427_RB.fastq/' _RB_GGAGATGTAC.fastq
rename 's/_RB_GGTGAAGAGA.fastq/BW-Combo3-428_RB.fastq/' _RB_GGTGAAGAGA.fastq
rename 's/_RB_GGGCTAACGA.fastq/BW-Combo3-429_RB.fastq/' _RB_GGGCTAACGA.fastq
rename 's/_RB_GGCGAACTTA.fastq/BW-Combo3-430_RB.fastq/' _RB_GGCGAACTTA.fastq
rename 's/_RB_GGATCCTGTA.fastq/BW-Combo3-431_RB.fastq/' _RB_GGATCCTGTA.fastq
rename 's/_RB_GGAAGACGGA.fastq/BW-Combo3-432_RB.fastq/' _RB_GGAAGACGGA.fastq
rename 's/_RB_GGACCACTGT.fastq/BW-Combo3-433_RB.fastq/' _RB_GGACCACTGT.fastq
rename 's/_RB_GGCGACACAC.fastq/BW-Combo3-434_RB.fastq/' _RB_GGCGACACAC.fastq
rename 's/_RB_GGAGCACCTC.fastq/BW-Combo3-435_RB.fastq/' _RB_GGAGCACCTC.fastq
rename 's/_RB_GGTGGAACAA.fastq/BW-Combo3-436_RB.fastq/' _RB_GGTGGAACAA.fastq
rename 's/_RB_GGGCTCGGTA.fastq/BW-Combo3-437_RB.fastq/' _RB_GGGCTCGGTA.fastq
rename 's/_RB_GGCGACTGGA.fastq/BW-Combo3-438_RB.fastq/' _RB_GGCGACTGGA.fastq
rename 's/_RB_GGATTGAGGA.fastq/BW-Combo3-439_RB.fastq/' _RB_GGATTGAGGA.fastq
rename 's/_RB_GGAAGGTACA.fastq/BW-Combo3-440_RB.fastq/' _RB_GGAAGGTACA.fastq
rename 's/_RB_GGAACGTGAT.fastq/BW-Combo3-441_RB.fastq/' _RB_GGAACGTGAT.fastq
rename 's/_RB_GGCGGATTGC.fastq/BW-Combo3-442_RB.fastq/' _RB_GGCGGATTGC.fastq
rename 's/_RB_GGAGCCATGC.fastq/BW-Combo3-443_RB.fastq/' _RB_GGAGCCATGC.fastq
rename 's/_RB_GGTGGCTTCA.fastq/BW-Combo3-444_RB.fastq/' _RB_GGTGGCTTCA.fastq
rename 's/_RB_GGGGAGAACA.fastq/BW-Combo3-445_RB.fastq/' _RB_GGGGAGAACA.fastq
rename 's/_RB_GGCGCATACA.fastq/BW-Combo3-446_RB.fastq/' _RB_GGCGCATACA.fastq
rename 's/_RB_GGCAACCACA.fastq/BW-Combo3-447_RB.fastq/' _RB_GGCAACCACA.fastq
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
rename 's/_RB_NA/NA_RB.fastq/' _RB_NA
